### ISSUE TITLE
[Bug] Investigate RelayMiner Issues

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#1006]
## Objective

Investigate & fix the issue identified during E2E PATH Testing.

## Origin Document

See the discord thread [here](https://discord.com/channels/824324475256438814/997192534168182905/1316576148032852131).

![Screenshot 2024-12-11 at 5 30 09 PM](https://github.com/user-attachments/assets/0750cabd-de8a-413d-8f4f-ff21c40a8dca)

![Screenshot 2024-12-11 at 5 30 14 PM](https://github.com/user-attachments/assets/7a647767-d629-421f-9404-b14b3f157507)

## Goals & Deliverables

- [ ] Identify the root cause in the issue above
- [ ] Implement a fix
- [ ] Improve the tooling and/or logs to make the issue clearer in the future
- [ ] If applicable, improve the tooling

## Deliverables

- [ ] Deliverable #1
- [ ] Deliverable #2

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas @adshmh @red-0ne

**Comment by red-0ne** [comment]
Closing as pr #1007
