### ISSUE TITLE
[AUDIT] Audit the Sparse Merkle Sum Tree

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#122]
## Objective

Audit the changes made to [Pocket Network's SMT](https://github.com/pokt-network/smt) after it was forked from [Celestia](https://github.com/celestiaorg/smt).

## Origin Document

From a conversation with the Celestia team:

![Screenshot 2023-10-31 at 3 51 18 PM](https://github.com/pokt-network/poktroll/assets/1892194/c954b3db-f8c8-42e4-996f-7ab9b646b72e)

From a conversation with the informal systems team

![Screenshot 2023-10-31 at 3 49 57 PM](https://github.com/pokt-network/poktroll/assets/1892194/fc53e4fe-852f-4bf1-a5a9-22968089cb9b)

## Goals

- Find a suitable auditing firm that fit our requirements
- Identify potential vulnerabilities in [pokt-network/smt](https://github.com/pokt-network/smt)

## Deliverables

- [ ] Understand the time, scope & cost of submitting an audit
- [ ] Identify a few potential auditing firms and select one
	- [ ] If choosing Informal Systems, fill out the [Pocket Network Audit Scope](https://docs.google.com/document/d/1Er-etnFdezFJ1axZlR5DuvOdDyRbrLi2dV2FR2P2bg4/edit#heading=h.k48agtlxk1af) provided by the Informal Systems team
- [ ] Submit & receive results of audit

## Non-goals / Non-deliverables

- Fixing the changes/issues raised by the audit
- Changing any business logic in the `poktroll` or `smt` repos
- Introducing or modifying any of the interfaces

---

**Creator**: @Olshansk 
**Co-Owners**: @h5law @RossiNYC

**Comment by RossiNYC** [comment]
@Olshansk - picking this up - reached out to Tesnim today - @h5law ETA on code complete here? Also looking for a few more options https://www.alchemy.com/list-of/blockchain-auditing-companies-on-cosmos and I tried to find "Binary Builders" as suggested by Ismail but can't seem to locate them anywhere (website, etc.) - I know its early but PNF is in 2024 budget review right now and I don't know what "a bit pricey" means!

**Comment by h5law** [comment]
@RossiNYC The library is complete in terms that it is ready to use in production, more features are planned but I think an audit on what is there currently is ideal before expanding even further. I would defer to @Olshansk judgement here but I'd say we are good to audit as it stands now.

**Comment by Olshansk** [comment]
>  I would defer to @Olshansk judgement here but I'd say we are good to audit as it stands now.

+1 to what @h5law said: we are ready for an audit now.

Any additional changes we make from here on are likely to be "superficial" w.r.t to the core business logic.

>  I know its early but PNF is in 2024 budget review right now and I don't know what "a bit pricey" means!

I had a conversation about this with Informal systems and never got an exact number.

@RossiNYC Can you get a rough ball park from Tesnim of what it would cost?

> and I tried to find "Binary Builders" as suggested by Ismail but can't seem to locate them anywhere (website, etc.)

Are you referring to [binary.builders](https://binary.builders/)?

> Also looking for a few more options [alchemy.com/list-of/blockchain-auditing-companies-on-cosmos](https://www.alchemy.com/list-of/blockchain-auditing-companies-on-cosmos) 

Please add [jepsen.io](https://jepsen.io/) to the list as well, though I don't know how much it would cost.

---

Unrelated, I reached out (both of you are CCeed) to the IOTA foundation for a potential grant to help fund this effort given that they're using the library which is a public good.

**Comment by RossiNYC** [comment]
You can now keep tabs on audit firm feedback/proposals here: https://www.notion.so/poktdao/Audit-SMT-6f4a5fd761ad4cfb91a2a2519776cc2a

**Comment by Olshansk** [comment]
@RossiNYC I've been getting ghosted by iota.

Can you potentially have Ben or Dermot see if they can help out here?

![Screenshot 2023-12-14 at 3 11 34 PM](https://github.com/pokt-network/poktroll/assets/1892194/da84c946-757a-4f63-9ea1-c137e75beea4)

**Comment by RossiNYC** [comment]
@Olshansk - will do on IOTA

**Comment by h5law** [comment]
@RossiNYC I dont have access to the notion you linked can you add me

**Comment by RossiNYC** [comment]
@Olshansk is this better? 

[POKT_Zellic_Proposal_20231212.pdf](https://github.com/pokt-network/poktroll/files/13715941/POKT_Zellic_Proposal_20231212.pdf)

**Comment by RossiNYC** [comment]
@Olshansk @h5law 
[EdenBlock 22-12-2023 Estimation.pdf](https://github.com/pokt-network/poktroll/files/13805801/EdenBlock.22-12-2023.Estimation.pdf)

**Comment by Olshansk** [comment]
@RossiNYC I looked over the documents and have a couple of questions.

1. The proposals all look templated & generic so I'm not quite sure what we should be using to evaluate the different companies. `Other than price & reputation, do you have any other suggestions on this?`

2. The price tags are really expensive given this is just the SMT library. `Can you ask what the price would be if it were for the entire poktroll repo as a reference point`?

**Comment by RossiNYC** [comment]
Informal Systems
[POKT Security Proposal.pdf](https://github.com/pokt-network/poktroll/files/13953746/POKT.Security.Proposal.pdf)

**Comment by RossiNYC** [comment]
Least Authority 
[Least Authority - Pocket Network_Sparse Merkle Tree Security Audit Proposal.pdf](https://github.com/pokt-network/poktroll/files/13954286/Least.Authority.-.Pocket.Network_Sparse.Merkle.Tree.Security.Audit.Proposal.pdf)

**Comment by Olshansk** [comment]
A lot of auditors asked us what to focus on in the audit, so adding those details here.

**1. Algorithmic vulnerabilities:** 
- Did the original SMT implementation we forked miss anything?
- Does the "closest proof" design from [1] have any vulnerabilities? NOTE: make sure to read the documentation in the repo.

**2. Implementation correctness:**
- Are there any bugs in the implementation of [1]?
- Do we need additional test coverage anywhere?

**3. Most important:** The above are just starting points. The "unknown unknowns" or "what we didn't think of" is where we could get the most value from your team's expertise.

[1] https://arxiv.org/abs/2305.10672

**Comment by Olshansk** [comment]
We have selected thesis.co as our audit partner and will keep track of future live documentation here: https://www.notion.so/buildwithgrove/Auditing-800f770ffbbc4453853ac74dc5a96a35?pvs=4
