### ISSUE TITLE
[Miner] Foundation for the Miner submodule

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#13]
## Objective

Create a foundation for the `Miner` submodule in the [poktroll](https://github.com/pokt-network/poktroll) repo for the Shannon upgrade.

## Origin Document

The business logic for mining relays from the [Relay Mining](https://arxiv.org/abs/2305.10672) paper.

## Goals

- Enable an E2E HTTP relay with basic session and account management
- Build the foundation for the `Miner` submodule for the `Relayer`
- Identify time-consuming TODOs to be done during the integration and testing stages

## Deliverables

- [ ] Reference structures and types in the [poktroll-alpha repo](https://github.com/pokt-network/poktroll-alpha), the [v1 repo](https://github.com/pokt-network/pocket) and [v0 repo](https://github.com/pokt-network/pocket-core) to understand and use other definitions as a foundation
- [ ] A **single PR** that introduces the `Miner` structure & interface
- [ ] A **single PR** that adds business logic, with the appropriate placeholders & TODOs, to add `Miner` functionality
- [ ] A **single PR** that integrates the miner with other components (e.g. `SessionManager`, `Proxy`, `Relayer`, `Client`, etc...) to enable E2E functionality
- [ ] A **single PR** that integrates with the [SMT](https://github.com/pokt-network/smt) for proof validation & verification
- [x] **Multiple small PRs** that migrate the necessary utilities from the `poktroll-alpha` repo to the `poktroll` repo

## Non-goals / Non-deliverables

- WebSocket support (HTTP only is okay)
- Accounting for all possible edge cases and situations

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite @red-0ne

**Comment by Olshansk** [comment]
@bryanchriswhite Looking at the deliverables of this ticket, I would argue it is not complete yet.

**Comment by bryanchriswhite** [comment]
@Olshansk agreed, thanks for re-opening. Are you aware of a way to prevent the issue from automatically closing when a linked PR is merged? Perhaps I should just not link them in the "development" section?

**Comment by bryanchriswhite** [comment]
```mermaid
---
title: Clients Dependency Tree
---
flowchart

sup[SupplierClient]
tx[TxClient]
bl[BlockClient]
evt[EventsQueryClient]

sup --"#SignAndBroadcast()"--> tx
tx --"#CommittedBlocksSequence()"--> bl
tx --"#EventsBytes()"--> evt
bl --"#EventsBytes()"--> evt
```

**Comment by Olshansk** [comment]
@bryanchriswhite I believe this was closed by accident, so I've reopened it.

Feel free to close if that was intentional.
