### ISSUE TITLE
[Research] BlockSci Research Questions

### ISSUE THREAD

**Issue by RossiNYC** [pokt-network/poktroll#134]
## Objective

Scope down the BlockSci research if possible by providing 3-5 pressing questions we have right now
Give BlockSci feedback on the test scenarios they have proposed (see Origin doc - Test Plan) 

## Origin Document

- [BlockSci Action Chains](https://docs.google.com/spreadsheets/d/11O-BMlL4XEyx4uLPf3nCKfy_c9tWaT2C0EajifZxumE/edit#gid=0)
- [BlockSci Test Scenario Plan](https://hackmd.io/@blockscience/SyI2DjJVp)

## Goals

1. Get some early learnings that could impact current Shannon development iterations
2. Focus on `Applications`, `Suppliers`, and/or `Gateways`

## Deliverables

- [x] 1. Question List
- [x] 2. Approval of test scenarios 

## Non-goals / Non-deliverables

1. Negatively impacting BlockSci progress
2. Running simulations

## General deliverables

- [ ] **Questions List**: Add/update TODOs and comments alongside the source code so it is easier to follow.

**Creator**: @RossiNYC

**Comment by RossiNYC** [comment]
On the [11/29 call](https://drive.google.com/file/d/1BL76JH29hq9ts1Zl1pK4gP_4eSlXYkZ7/view?usp=drive_link) PNF approved the following scenarios in this priority order: 

1. Servicer (Supplier) viability
2. Network viability - Rewards & Fees
3. Gateway viability 
4. Network failures - servicer (supplier)
5. Network failures - oracle
6. Jailing/Slashing (of Suppliers) 

The following questions were put forward:

1. How does node difficultly / cost to operate impact supplier viability? (PNF followed up with supporting research from a recent node runner survey) 
2. How would an economic gaming of the oracle impact the network, would there be a way to identify this? 
3. Do the current reward and fee structures support all actors positively (under what conditions can any supplier and/or gateway earn a positive return) 

POKT to Clarify:
Open questions around pausing vs. jail/slashing of nodes - will suppliers or other malicious actors in the ecosystem be subject?

**Comment by Olshansk** [comment]
> Open questions around pausing vs. jail/slashing of nodes - will suppliers or other malicious actors in the ecosystem be subject?

`Jailing` - This should be treated this as a state that's derived by the result of some exogenous variable (e.g. RPC challenge, but out-of-scope) that will result in slashing.

`Pausing` - This is a supplier-initiated state and TBD if we'll implement it. If we do, there may be a mechanism that transitions` Pasuing -> Jailing` (e.g. one of various factors leading to a Jailing) if it is present for too long.
