### ISSUE TITLE
[Infra] Enable E2E Relay Load Testing on LocalNet

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#135]
## Objective

Set a foundation for load testing relays on LocalNet to enable all downstream efforts.

## Origin Document

The following tools were provided by the backend & infra teams at Grove as a reference:
- https://github.com/pokt-foundation/rpc-k6/blob/master/README.md
- https://github.com/pokt-foundation/rpc-k6/blob/master/tests/src/smoke.js
- https://github.com/pokt-foundation/rpc-k6/blob/master/tests/src/ws.js

## Goals

- Set the foundation for all future load-testing efforts of the Shannon upgrade
- Enable us to start getting some data on how much load the network can handle and start facing potential issues
- Identify or develop a load-testing tool compatible with our stack (coordinate with Grove team)
- Enable customizable transaction types, frequency, and volume for load tests
- Enable customizable relay frequency and volume for load tests
- Ensure compatibility with LocalNet for testing

## Deliverables

- [x] Select a tool (framework, library, build, etc...) to load test E2E relay
- [x] Provide a mechanism (command, script, etc...) to load test relays
- [x] Selection or creation of a load-testing tool after consulting with Grove team
- [ ] Implement a feature to customize and trigger load tests for transactions
- [ ] Implement a feature to customize and trigger load tests for relays
- [ ] Validate that the load-testing tool and features are usable on LocalNet

## Non-goals / Non-deliverables

- Randomizing the relay type being sent
- Enabling E2E Relay load testing on DevNet
- Telemetry & observability into how the node behaves

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas

**Comment by Bidon15** [comment]
Hey @Olshansk 
How long should time wise each load test lives? If you need just to spin-up nodes without much bandwidth limitations and start loading nodes, then a good starting point is 

https://github.com/celestiaorg/knuu

Examples: https://github.com/celestiaorg/knuu-example

If you need bandwidth limitations, then you should be interested in 
https://github.com/testground/testground
https://github.com/testground/infra

Both knuu and testground use k8s for orchestration of nodes under test. 
If you want to simulate traffic with random amount of TXMsgTypes, you can use this txsim and adapt according yo your needs https://github.com/celestiaorg/celestia-app/tree/main/docker

**Comment by Olshansk** [comment]
@Bidon15 Thanks for the reply, details and links!

The initial test will be focused on pushing some on-chain processing to its limits, so `knuu` is definitely where we'll start.

@okdas @bryanchriswhite and I will be putting together a load testing design doc in the coming weeks and will definitely follow up with questions once we give these tools a shot!
