### ISSUE TITLE
[Protocol] Claim & Proof Lifecycle Governance Params

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#142]
## Objective

Introduce all the governance params needed for the claim and proof lifecycle.

## Origin Document

Governance params from [Morse](https://github.com/pokt-network/pocket-core) can be identified using the following helpers.

```bash
POCKET_ENDPOINT=https://mainnet.gateway.pokt.network/v1/lb/60a2ac11b1747c6552385c61

function get_pocket_param() {
    local param_key="$1"
    pocket query params --remoteCLIURL ${POCKET_ENDPOINT} | tail -n +2 |
        jq --arg key "$param_key" '.[] | .[] | select(.param_key==$key) | .param_value'
}

function get_all_param_keys() {
    pocket query params --remoteCLIURL ${POCKET_ENDPOINT} | tail -n +2 |
        jq -r '.[] | .[].param_key'
}
```

## Goals

- Have Shannon achieve feature Parity w/ Morse in terms of governance w.r.t to the claim & proof lifecycle
- Tend to TODOs that prevent the Claim & Proof lifecycle from being `TestNet` ready

## Deliverables

- [ ] Research work that identifies & documentation the necessary governance params for the Claim & Proof Lifecycle
- [ ] A single PR that introduces the governance parameters above on-chain
- [ ] A single PR that updates all techdebt / TODOs in the on-chain logic based on the parameters above
- [ ] A single PR that updates all techdebt / TODOs in the off-chain logic based on the parameters above

## Non-goals / Non-deliverables

- Introducing more parameters or features than necessary for optimizing the Claim & Proof lifecycle

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite @red-0ne  @RossiNYC

**Comment by bryanchriswhite** [comment]
@Olshansk can this be closed? I think it's done but am not certain due the way it's phrased.

**Comment by bryanchriswhite** [comment]
Closing for now, to reopen if needed.
