### ISSUE TITLE
[Migration] wPOKT Migration strategy

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#145]
## Objective

Prepare a migration strategy for the `wPOKT` bridge.

## Origin Document

- Related to #144
- There are lots of `wPOKT` libraries which 
	- https://github.com/pokt-network/wpokt-staking-frontend
	- https://github.com/pokt-network/wpokt-staking-frontend
	- https://github.com/pokt-network/wpokt-frontend
	- https://github.com/pokt-network/wpokt-frontend
	- https://github.com/pokt-network/wpokt-staking-contracts
	- https://github.com/pokt-network/wpokt-monitor
	- https://github.com/pokt-network/wpokt
	- https://github.com/pokt-network/wpokt-validator
	- https://github.com/pokt-network/wpokt-subgraph

## Goals

- Research and identify unknown unknowns for the bridge migration
- Start preparing a plan for how the wPOKT bridge should be migrated

## Deliverables

- [ ] A 2-pager determining how the wPOKT bridge should be migrated
- [ ] A stakeholder that will own the migration from Morse to Shannon
- [ ] The alternative selected (e.g. Axelar) for Ethereum interoperability after the Shannon migration

## Non-goals / Non-deliverables

- Doing the actual migration
- Build out the infrastructure for the post-migration EVM interoperability

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @RossiNYC

**Comment by RossiNYC** [comment]
Current plan coming out of the PNF offsite is that Matteo will reach out to Raid Guild for feedback here.

**Comment by RossiNYC** [comment]
Wrote up this RFP https://docs.google.com/document/d/17PTh01Vf3aL0V-bfXTMU5cPt3wf0dXWCJuvDHAFCwSA/edit and will provide to Raid Guild - looking for a few other options as well.

**Comment by Olshansk** [comment]
@RossiNYC Saw your starting point for the RFP. As we discussed offline, definitely a lot more to unpack and think through here. I think that when the time is right, it might be worth preparing a list of questions for raidguild and "consulting" them on our options.

**Comment by Olshansk** [comment]
@RossiNYC Something to consider is that if we end up partnering we an interoperability project (e.g. hyperlane), we could ask them to own/drive this work for us as well. Wdyt?

**Comment by RossiNYC** [comment]
@Olshansk - yep, agreed. Have been speaking with Dermot about this - the decision tree is something like: 
Figure out our bridging strategy based on PNF wPOKT Strategy (what/where do they want it listed, etc.) 
Based on that - we could either a. use a team like RG to migrate or b. engage a project (hyperlane, etc.) or c. do both
I have a followup with Dermot/Ben on Wed (Dec 13) to discuss this more - TL;DR - we are aligned on option b 100%

**Comment by RossiNYC** [comment]
Spoke with RG today (w/Dermot) - they will help us with defining the migration strategy and sequence of events - they will also help evaluate interop propto's like Hyperlane - main ask was around us supporting EVM at the rollup layer (Polaris for e.g.) as even deploying Hyperlane would be easier - they have some strong opinions on security and though that the rollup supporting EVM would help "reduce attack surfaces" 

Open Questions:
Will Ledger support the new pocket network? (A. YES) 
When it comes the RPC calls changing, does that mean the url extensions of each request in the code below will change? Will the data (aka the request body) section change? And will the JSON format for the response data of each change?

```
javascript=
requests = {
    getBalance: (address, height) => ({
      url: "/v1/query/balance",
      method: "post",
      data: {
        address,
        height,
      },
    }),
    getTransaction: (id) => ({
      url: "/v1/query/tx",
      method: "post",
      data: {
        hash: id,
      },
    }),
    sendRawTx: (fromAddress, tx) => ({
      url: "/v1/client/rawtx",
      method: "post",
      data: {
        address: fromAddress,
        raw_hex_bytes: tx,
      },
    }),
    getSupportedChains: (height) => ({
      url: "/v1/query/supportedchains",
      method: "post",
      data: {
        height,
      },
    }),
  };
```

**Comment by Olshansk** [comment]
> they will also help evaluate interop propto's like Hyperlane

Sounds good. 

However, personally, given that Hyperlane & Axelar are the big players and our selected sequencer is partnering with Hyperlane, I'm not sure there's a lot of value to this investigation.

> ask was around us supporting EVM at the rollup layer (Polaris for

I asked for an intro to the Polaris team in our channel with Rollkit on slack.

> When it comes the RPC calls changing, does that mean the url extensions of each request in the code below will change? Will the data (aka the request body) section change? And will the JSON format for the response data of each change?

Yes. Everything will change. Shannon is a complete rewrite.

**Comment by RossiNYC** [comment]
X-Ref the corresponding Discord channel to this issue: https://discord.com/channels/553741558869131266/1187104966826008696
