### ISSUE TITLE
[SDK] Integrate Grove's Portal into the poktroll Repo

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#158]
## Objective

Run Grove's portal as part of this repo's (i.e. the Shannon upgrade) LocalNet & DevNet infrastructure with automated E2E Relays.

## Origin Document

The Shannon Upgrade equivalent of the "SDK" is being implemented in [poktroll/tree/main/pkg](https://github.com/pokt-network/poktroll/tree/main/pkg) and serves as the integration point for any future Gateways, including Grove's portal.

## Goals

- Identify missing gaps in the MVP SDK necessary portal integration
- Streamline portal deployment in both local & remote environments for regression testing
- From @ezeike: I would consider this issue a success if the SDK has progressed to a point where our gateway is able to use it to dispatch sessions and send relays via localnet.

## [New] Deliverables

- [ ] A `Makefile` target that dispatches a session and sends a relay via the portal through a LocalNet

## [Deprecated] Deliverables

- [ ] [@kutoft et al] Support Portal deployment in Shannon's LocalNet
- [ ] [@red-0ne] Updates to `AppGate` necessary for Portal integration
- [ ] [@h5law] E2E tests to make sure the portal is part of the ring signature
- [ ] [@okdas] Deploy Grove's Portal as part of the LocalNet & DevNet infrastructure
- [ ] [@Olshansk] Document the portal's integration in this repo 

## Non-goals / Non-deliverables

- Supporting all possible use cases (e.g. QoS) as part of the deployment & integration
- Create a general-purpose gateway integration

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @kutoft @okdas @red-0ne @h5law

**Comment by Olshansk** [comment]
**Documentation to shared:**
- SDK
- Swagger
- OpenAPI spec

**Examples to provide:**
- Example of dispatching
- Example of relay

**Comment by Olshansk** [comment]
**Rought Notes** / Ideas from a conversation with @red-0ne:
- **Idea**: Is forking the portal a good direction?
- **Keep in mind**: APIs, SDK, etc are amorphous and ill-defined
- **North star**: get portal running on LocalNet/ DevNet
- **Define direction for**: Provide a good SDK / documentation for future gateways in the future
- **Define direction for**: Determine what an SDK will look like
- **Question for portal**:
	- Where is the code?
	- What kind of modules are available?
	- What is the E2E flow?

**Comment by Olshansk** [comment]
![Screenshot 2023-11-17 at 3 30 15 PM](https://github.com/pokt-network/poktroll/assets/1892194/68435457-0c3f-450f-834a-8847c8c0967d)

The digram above captures where the focus on the integration points will be in this effort.

[This notion doc](https://www.notion.so/buildwithgrove/Giga-Stakes-be14fdc39f6a452da3d4c4f831cf71fe?pvs=4) captures the action items that we'll cover.

**Comment by Olshansk** [comment]
Cross-posting an update from @ezeike in discord:
* PR for Shannon relays: https://github.com/pokt-foundation/portal-middleware/pull/517
* Grove Gateway migration status/plan: https://www.notion.so/buildwithgrove/Grove-Gateway-Status-f934e12f97014e1a8d754575a3fdaabd
* Intro to Shannon (aimed at backend & non-protocol folk): https://www.notion.so/buildwithgrove/Intro-To-Shannon-c5523f9519424fcfab8277b187fb6cb4
* Giga-stakes exploration post Shannon: https://www.notion.so/buildwithgrove/Chain-Aliases-ServiceIDs-Gigastaked-Applications-e1a0725366b645f0a54d67940522686a

Next steps: enable the QoS module by mapping v0 <-> v1 types.

@ezeike 👍 or did I miss something? cc @red-0ne for context

**Comment by Olshansk** [comment]
@ezeike Can you link to the PR you're working on once it's ready?

**Comment by Olshansk** [comment]
@ezeike What do you consider the success criteria for this?

**Comment by ezeike** [comment]
PRs and status are being tracked in this discord channel:

https://discord.com/channels/824324475256438814/1201948542768259142

In the time since this issue was created it was decided the grove gateway won't be integrated into the poktroll repo, we can disregard that portion of this issue.

I would consider this issue a success if the SDK has progressed to a point where our gateway is able to use it to dispatch sessions and send relays via localnet.

**Comment by Olshansk** [comment]
@ezeike Soudns good.

> I would consider this issue a success if the SDK has progressed to a point where our gateway is able to use it to dispatch sessions and send relays via localnet.

I have updated the deliverables & goals to reflect this.

**Comment by Olshansk** [comment]
Updated requirement: @ezeike will create a makefile target that can send a really through the portal and there will be a link to a log to observe it.
