### ISSUE TITLE
[Testing] E2E Testing Framework

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#16]
## Objective

Migrate the previously built E2E Testing framework to this repo.

## Origin Document

The [pocket repo](https://github.com/pokt-network/pocket) implements an [E2E testing framework](https://github.com/pokt-network/pocket/tree/main/e2e) that needs to be migrated to the poktroll repo.

## Goals

- Enable E2E regression testing
- Enable automation that'll be used in load testing

## Deliverables

- [x] A single PR that adapts [this directory from the v1 repo](https://github.com/pokt-network/pocket/tree/main/e2e) to this repository
- [x] A single PR that introduces an E2E test for staking/unstaking
- [ ] A single PR that introduces an E2E test for a relay that verifies on-chain claims & proofs

## Non-goals / Non-deliverables

- Provide the tooling for every type of E2E Test that we may need
- Automated E2E tests in our CI/CD pipeline

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite @red-0ne @h5law

**Comment by Olshansk** [comment]
@h5law As I was working on #59, I saw that there is a lot of infra & utils to do things like (for example)

1. Run simulation ([advanced simulation link](https://docs.cosmos.network/main/learn/advanced/simulation))
2. Startup a mock network in tests for a CLI context (e.g. see `x/application/client/cli/helpers_test.go` in #59 and code below)

My added ask/requirement is if you could research & look into those as well (as you're enabling a cucamber/gherking development framework) to make sure we leverage as much as possible of Cosmos' infrastructure and don't recreate the wheel.

---

```go
func networkWithApplicationObjects(t *testing.T, n int) (*network.Network, []types.Application) {
	t.Helper()
	cfg := network.DefaultConfig()
	state := applicationModuleGenesis(n)
	buf, err := cfg.Codec.MarshalJSON(state)
	require.NoError(t, err)
	cfg.GenesisState[types.ModuleName] = buf
	return network.New(t, cfg), state.ApplicationList
```

**Comment by h5law** [comment]
> My added ask/requirement is if you could research & look into those as well (as you're enabling a cucamber/gherking development framework) to make sure we leverage as much as possible of Cosmos' infrastructure and don't recreate the wheel.

@Olshansk From my understanding the purpose of the E2E suite was to test outside of simulations using the localnet environment and the CLI. Are you suggesting we change this?

**Comment by Olshansk** [comment]
> From my understanding the purpose of the E2E suite was to test outside of simulations using the localnet environment and the CLI.

That is correct.

> Are you suggesting we change this

Nope, I'm suggesting that we explore whether the simulation library (or other tools in the cosmos SDK ) enable it without us having to recreate the wheel. I don't know whether this is possible or a complete dead-end, but it's hard to know without diving deeper into the tools.

I know intuitively you might think `Obviously it's completely different`, but I'm not 100% convinced as I'm not an expert in all the test utilities Cosmos has to offer yet.

**Comment by h5law** [comment]
>  I don't know whether this is possible or a complete dead-end, but it's hard to know without diving deeper into the tools.

I will keep it in mind, currently making a staking e2e test, but will look into simulations alongside your research into it to see how we can benefit from it. I would need to see some examples of other chains using it well so will try to find some. Currently from the few I've looked at some don't even simulate at all.
