### ISSUE TITLE
[AppGate] Add config file for AppGate server daemon

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#203]
## Objective

Productionize the AppGate server configuration directives

## Goals

- Enable a better interface than CLI flags for configuring and starting the AppGateServer

## Deliverables

- [ ] A Configuration flag for the AppGateServer daemon to source its config directive from a yaml file

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @red-0ne

**Comment by Olshansk** [comment]
@red-0ne I saw the goals & deliverables you had and want to update them.

Previously, you had these.

![Screenshot 2023-11-21 at 4 15 29 PM](https://github.com/pokt-network/poktroll/assets/1892194/8f51f92b-e11d-44fc-b016-29772f8ecb23)

I would expand it like so

```
Goals
* Enable a better interface than CLI flags for configuring and starting the `AppGateServer`
* Code as documentation for community members
* Reusable and more maintainable configuration for Gateway maintainers

Deliverables
- [ ] A Configuration flag for the AppGateServer daemon to source its config directive from a yaml file
- [ ] Examples of `AppGateServer` configuration files in LocalNet
- [ ] Documentation on `AppGateServer` config files and options
```

I realize that you might say the above is:
- Obvious for anyone reading this
- We were planning to do it anyhow
- We were just creating a quick ticket as a placeholder and didn't want to spend time on the above

I agree with all of the above, but in practice, have simplify found that spending the extra (painful, not easy) time on explicitly stating goals & deliverables goes a long way in communicating/collaborating with others.
