### ISSUE TITLE
[RelayMiner] Add config file for RelayMiner

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#205]
## Objective

Productionize the RelayMiner configuration directive and allow them to specify proxied services endpoints

## Goals

- Enable a better Ops experience by allowing operators to specify different aspects/configurations of the RelayMiner in a yaml file

## Deliverables

- [ ] A PR with the feature and tests that enables configuring the RelayMiner from a yaml config file

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @red-0ne

**Comment by Olshansk** [comment]
@red-0ne I'm beginning to lose picture of all the different configs and why we have them so I think a README with examples is becoming a higher priority. Here's what I see so far:

Staking configs:
- `App` config -> for `staking` applications
- `Gateway` config -> for `staking` gateways
- `Supplier` config -> for `staking` suppliers

Operations configs:
- `AppGate` config -> for `operating` a gateway or an application
- `RelayMiner` config -> for `operating` a supplier

**Comment by Olshansk** [comment]
> Exactly. Haven't worked on anything regarding Gateway config though.

- #224
