### ISSUE TITLE
[Testing] migrate from golang/mock to uber-go/mock

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#208]
## Objective

[ What? Describe the issue in 1-2 sentences]

## Origin Document

[ Why? Justify the issue in 1-2 sentences. Consider adding a link or a screenshot.]

## Goals

- ...

## Deliverables

- ...

## Non-goals / Non-deliverables

- ...

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@bryanchriswhite Because you ask me to remind you - friendly reminder that you can just insert screenshots as origin documents.

**Comment by Olshansk** [comment]
Closing because it's unlikely this will be in scope anytime soon. Can always reopen if need be.
