### ISSUE TITLE
[Flaky Test] TestRelayerSessionsManager_Start

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#217]
## Objective

Minimize wasted CPU and person-time on CI re-rolls.

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/600733/f7a066b9-a3b6-4c2a-aeec-3ab11035ef6d)
> **Fig. 1**: [#210 Attempt #3](https://github.com/pokt-network/poktroll/actions/runs/6966779144/job/18957989934); see also [#210 Attempt #2](https://github.com/pokt-network/poktroll/actions/runs/6966779144/job/18957786828).

![image](https://github.com/pokt-network/poktroll/assets/600733/29fd8ff5-8011-4f00-a4a0-6a1a0d81b1ba)
> **Fig. 2**: Attempt to reproduce Fig. 1 locally using `make itest 40 10 ./pkg/relayer/session -- -run=RelayerSessionManager_Start`

## Goals

- Enumerate flaky failure modes present.
- Eliminate each (as measurable, ideally 0:10000 or better failure-to-success test trial ratio).

## Deliverables

- One or more PRs which address the flaky failure mode(s).

## Non-goals / Non-deliverables

- Refactoring implementation or test code outside the scope of addressing flakiness.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**:

**Comment by Olshansk** [comment]
Will keep an eye out for this. Thanks @bryanchriswhite!

**Comment by Olshansk** [comment]
Tracked in TODOs.
