### ISSUE TITLE
[Gateway] Add config for `Gateway`

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#224]
## Objective

Productionize the RelayMiner configuration directive and allow them to specify proxied services endpoints

## Goals

- Enable a better Ops experience by allowing operators to specify different aspects/configurations of the RelayMiner in a yaml file

## Deliverables

- [ ] A PR with the feature and tests that enables configuring the RelayMiner from a yaml config file

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk
**Co-owner**: @red-0ne

**Comment by red-0ne** [comment]
We don't have `Gateway` config yet, as it only involves stake amount.

It will be addressed with #293
