### ISSUE TITLE
[Service] Require payment when staking for a new service

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#230]
## Objective

Prevent permissionless Sybil attacks by the introduction of new services.

## Goals

- Disincentivize Sybil attacks on the network
- Allow Pocket Network to scale to any number of actors/services permissionlessley
- Prevent state/chain bloat by allowing applications to introduce an infinite number of new services on the network

## Deliverables

- [ ] Introduce a new `AddService` command on the network that allows anyone (actor or not) to stake a new `serviceID` in exchange for some fee (a governance param)
- [ ] Block/fail/ignore any on-chain state transition that is performed for `serviceId` that has not been added.

## Non-goals / Non-deliverables

- Modelling out all the tokenomic 'repercussions' of this feature

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @h5law @RawthiL

**Comment by RossiNYC** [comment]
@Olshansk - who collects the fee here? PNF?

**Comment by Olshansk** [comment]
> @Olshansk - who collects the fee here? PNF?

It will either be burnt or paid to the DAO.
