### ISSUE TITLE
[Integration Tests] Re-architect and re-factor `integration tests`

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#255]
## Objective

Define the line between `integration tests` and `E2E tests`, and update the codebase to reflect those changes.

## Origin Document

This is followup to some of the work & exploration done in `pkg/client/delegation/client_integration_test.go` as part of #220 and relates to this comment

![Screenshot 2023-12-10 at 3 29 15 PM](https://github.com/pokt-network/poktroll/assets/1892194/51856750-2575-41d1-bc94-a0fb8659ffb0)

## Goals

- Clearly identify the distinction between `unit tests` (i.e. no network), `integration tests` (i.e. in-memory network) and `E2E tests` (i.e. local network)
- Define patterns and helpers to implement integration tests in the future easily
- Avoid using `LocalNet` in `integration tests` and reserve that for `e2e tests`

## Deliverables
- [ ] Document the difference between `unit tests`, `integration tests` and `e2e tests`
- [ ] A PR that re-factor `NewLocalNet` and related helpers after determining how `integration tests` should be designed
- [ ] A PR that enables existing `integration tests` in our CI (skipping failing integration tests w/ TODOs)
- [ ] Separate PRs for each test (or helper refactor, etc.) to fix failing integration tests and/or complete in-progress integration tests from #220.
- [ ] ~~A PR that refactors `TxClient` to be a `ReplayClient`~~ (see: #256)

## Non-goals / Non-deliverables

- Adding new integration tests
- Adding new e2e tests
- Adding new functionality

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite @h5law

**Comment by Olshansk** [comment]
@bryanchriswhite Can you review the goals & deliverables and let me know if it captures what's needed in conjunction with what you had in mind.

**Comment by bryanchriswhite** [comment]
![image](https://github.com/pokt-network/poktroll/assets/600733/09088786-813f-4f0d-b371-83c8e1e2cb5b)

Given my current understanding, I agree that it makes sense to remove the `integration` tag from "integration" tests as they SHOULD, by definition, not depend on localnet/devnet.

**Comment by bryanchriswhite** [comment]
Relates to:

- #266 
- #250

**Comment by Olshansk** [comment]
@bryanchriswhite While continuing to learn & understand the Cosmos SDK source, I came by [1].

I haven't looked at the overlap or inter-dependencies in code / approach between what we have and [1], but wanted to understand if:
1. Is there overlap here?
2. Should we consider leveraging this approach or keep following what we have in flight?

[1]  https://github.com/cosmos/cosmos-sdk/blob/main/tests/integration/distribution/keeper/msg_server_test.go#L47

**Comment by Olshansk** [comment]
We've got this figured out now after the migration.
