### ISSUE TITLE
[Misc] Explore Cosmos ecosystem explorers

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#27]
## Objective

Explore solutions for a Pocket blockchain exploration UI.

## Origin Document

Using the Cosmos SDK, a lot of tools such as [react](https://docs.ignite.com/clients/react) and [vue](https://docs.ignite.com/clients/vue) frontends become available. There are likely many other tools (e.g. block explorer, wallets, etc..) that we should look into for pocket.

## Goals

- Assess existing blockchain exploration tools
- Evaluate the capability of incorporating Pocket-specific utility data

## Deliverables

- [ ] Document findings on suitable solutions
- [ ] Create a new ticket for implementation based on findings

## General deliverables

- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @okdas
**Co-owner**: @Olshansk

**Comment by Olshansk** [comment]
Part of this work should also look into surfacing on-chain events in the block explore + a good use-case for it from an observability/data POV.

> Events are objects that contain information about the execution of the application. They are mainly used by service providers like block explorers and wallet to track the execution of various messages and index transactions.

Ref: https://docs.cosmos.network/v0.50/learn/advanced/events

**Comment by Olshansk** [comment]
Just came by this one which seems to be used by a lot core chains including Akash and others: https://github.com/fetchai/cosmos-explorer

**Comment by Olshansk** [comment]
![Screenshot 2023-10-30 at 11 56 22 AM](https://github.com/pokt-network/poktroll/assets/1892194/c7f673fd-0945-4899-9a2c-85d5c97290e4)

![Screenshot 2023-10-30 at 11 56 28 AM](https://github.com/pokt-network/poktroll/assets/1892194/2251db65-9af6-4ec1-be98-80830c6c8153)

**Comment by Olshansk** [comment]
@okdas The Celestia team is going to introduce us to two projects we should heavily consider w.r.t block explorers:

- https://www.blockscout.com/
- https://celenium.io/

**Comment by RossiNYC** [comment]
There is also: https://atomscan.com/about (not sure what the qualification criteria is...) and 
https://cosmostation.io/products/mintscan (which actually looks pretty good)

**Comment by Olshansk** [comment]
I looked through the list of explorers [lava is using](https://docs.lavanet.xyz/block-explorer/) and also came by explorers.guru.

**Comment by Olshansk** [comment]
Adding a note from @h5law about mintscan so it doesn't get lost.

Once we're both Cosmos SDK and IBC compatible there's an opportunity to leverage both types of explorers:
- Ones that we deploy and customize ourselves on our own domain such as [blockscout.com](https://www.blockscout.com/)
- Ones that aggregates several Cosmos/IBC projects such as [mintscan.io](https://www.mintscan.io)

**Comment by bryanchriswhite** [comment]
https://buildwithgrove.notion.site/Poktroll-Explorer-Architecture-5e8f667fcd8d42979b1070dc7279fa63?pvs=4

**Comment by qspider** [comment]
Exploring different architecture. Particularly interested in Vue/Django REST server but have open mind for tooling.

**Comment by moatus** [comment]
https://ping.pub/ instance has been deployed by @icculp: https://poktroll-devnet.cryptonode.tools/

**Comment by moatus** [comment]
Ping.Pub explorer for testnet is live: https://poktroll-devnet.cryptonode.tools
