### ISSUE TITLE
[Code Health] Standardize & enforce golang import linting

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#270]
## Objective

Standardize & enforce imports across the codebase

## Origin Document

This is the result of several discussions from #253:

![Screenshot 2023-12-13 at 12 59 38 PM](https://github.com/pokt-network/poktroll/assets/1892194/20b0785d-21b2-42dd-8119-89e5d344beab)
![Screenshot 2023-12-13 at 12 59 20 PM](https://github.com/pokt-network/poktroll/assets/1892194/4c14dea2-9e7e-43dc-be22-ff5bb707273e)

## Goals

- Standardize & enforce imports across the codebase
- Enforce the same import rules across local development & CI for all users
- Make it easy/trivial for any developer to adopt the same import linting rules & practices

## Deliverables

- [ ] Select the type golang import rules / tool / server we'll be using (e.g. `gofmt`, `goimport`, etc...)
- [ ] Update the CI to block/enforce the selected styling
- [ ] Update `make go_imports` to use the select tool
- [ ] Document (or link to) how developers can configure their development environments to enable the selected tool on their machines (e.g. JetBrains, neovim, vscode, etc...)

## Non-goals / Non-deliverables

- Document all possible IDE configurations (just the ones you're using)

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite @h5law

**Comment by h5law** [comment]
Tools that I use that seem to be what we are looking for:

https://pkg.go.dev/github.com/incu6us/goimports-reviser#section-readme

This sorts imports the way we want them to be

https://github.com/yoheimuta/protolint

For protobufs - imports and lints very nicely (considers import order too)

**Comment by Olshansk** [comment]
@h5law After we merge in #252, let's add a page / section called devtools so all contributors can have the same configs.

**Comment by bryanchriswhite** [comment]
See  https://github.com/pokt-network/poktroll/pull/283#issuecomment-1865796092
![image](https://github.com/pokt-network/poktroll/assets/600733/023000df-91c6-4781-b920-38686c232ce5)
