### ISSUE TITLE
[Configs] Align & standardize how to maintain & manage generated protobufs 

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#276]
## Objective

Determine if/where/how auto-generatd protobufs should be maintained and tend to those tasks.

## Origin Document

Different projects & code bases have different practices on whether autogenerated code should or should not be merged into main. Up until now, the practice in this repo has been to `gitignore` all `.pb.go` files.

<img width="863" alt="Screenshot 2023-12-14 at 4 28 21 PM" src="https://github.com/pokt-network/poktroll/assets/1892194/98670931-3e48-484a-bb5b-0ed761214d95">

![Screenshot 2023-12-14 at 4 40 38 PM](https://github.com/pokt-network/poktroll/assets/1892194/7f7c2967-709e-490f-ae94-c17b105325e5)

## Goals

- Decide, document & standardize how auto-generated code should be managed in the `poktroll` repo
- Avoid newcomers to the code to need to have institutional knowledge of what/how to do to maintain auto-generated code correctly

## Deliverables

- [ ] Document the reasons in favour & against committing auto-generated code
- [ ] Document the decision made on next steps
- Whether there's a change or not:
	- [ ] Update all the tools (e.g. Makefile) to reflect the decision made
	- [ ] Update all the CI tools to reflect the decision made
	- [ ] Update all the documentation to reflect the decision made

## Non-goals / Non-deliverables

- Introducing any new SDK functionality

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @red-0ne @ezeike

**Comment by Olshansk** [comment]
@ezeike

1. Any updates on this?
2. Is this an immediate blocker?
3. Which iteration do you think we'll tackle it in. If unsure or it's not a priority, can you remove the iteration # please.

**Comment by ezeike** [comment]
I think it makes sense to commit the auto-generated code to the repo. Doubly so if it's what other IBC projects are doing.

- Regenerating the .pb.go files is not something gateway builders have a reason to be doing. There's no customization possible or options available and likely most if not all gateways will be written in go.
- Having the .pb.go in gitignore means some/most editors will also ignore those files, creating an extra hassle for developers.

This is not an immediate blocker. When there's both a testnet and we want to deploy our gateway to the staging environment then it would be as our gateway won't have access to the .pb.go files.

**Comment by Olshansk** [comment]
@ezeike Thanks for the reply.

1. Removing the iteration for now.
2. Adding this to [Questions to the community](https://www.notion.so/buildwithgrove/WIP-Questions-to-from-the-Community-c547575002ea45529c563bd725072258?pvs=4), and we'll revisit when the time is right or this becomes a priority again.

**Comment by Olshansk** [comment]
No longer a priority
