### ISSUE TITLE
[AppGate] Add a grace period where delegation changes don't apply until the end of the Proof/Claim lifecycle

### ISSUE THREAD

**Issue by h5law** [pokt-network/poktroll#279]
## Objective

In order for the session to be able to continue with the correct rings any delegation changes should not occur on-chain until the next session for the given application. However, as the proof of a session also needs the ring to validate signatures this grace period **must** extend until the proof has been validated as well. Meaning that delegation cannot change when in a session until after the claim/proof lifecycle of that session has completed.

Utilising as much of the cosmos-sdk features as possible implement a grace period such that any delegation changes are finalised after the current session ends for an application.

## Origin Document

Related issue https://github.com/pokt-network/poktroll/issues/73

## Goals

- Utilise the SDK to implement a grace period where applications who are changing their delegation status finalise this change when their current session ends.

## Deliverables

- [ ] Produce Diagrams detailing how the grace period should look w.r.t the session and claim and proof lifecycle.
- [ ] A working Grace period (name TBD)
- [ ] Little in-house work done (utilise the SDK as much as possible)
- [ ] Update #73 with the learnings from this implementation

## Non-goals / Non-deliverables

- Change anything outside of the on-chain logic
- Break any (un)delegation logic
- Break ring building
- Break any session logic

## General deliverables

- [x] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [x] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @h5law 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@h5law I thought about this and think that we can get into a LOT of complexity and edge cases if you take into account the following (and any permutations it might encompass):

* Delegation grace periods
* Unstaking / staking
* Changes to the `blocksPerSession` parameter
* Session rollovers
* Other features we'll add in the future

I also know that time-delayed operations are prone to increasing bugs and complexity.

Before you jump into the implementation, can you provide a 1-pager design with the approach you're thinking of taking?

---

CC @red-0ne who is looking into #275 with me.

**Comment by h5law** [comment]
See 1 for reference on how staking undelegation is done

[1] https://docs.cosmos.network/main/build/modules/staking#unbondingdelegation

**Comment by Olshansk** [comment]
No longer needed
