### ISSUE TITLE
[Testing] Flakey integration tests (in-memory network)

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#295]
## Objective

Capture unique instances of flakey integration tests, which by definition are using the in-memory cosmos network integration (see #290).

## Origin Document

1. `TestListGateway`:
  ![image](https://github.com/pokt-network/poktroll/assets/600733/d2b92711-dd92-4ff0-ad42-a25379244c48)

## Goals

- Enumerate flakey tests which are likely attributable to issues in the in-memory cosmos network integration as such observations will:
  - Contribute describing the failure mode(s) present 
  - Establish a comprehensive and robust baseline sufficient for confirming the elimination of failure mode(s)

## Deliverables

- [ ] Accumulate failure results in this issue until it is prioritized, categorizing failure modes as they become apparent.
- [ ] A PR targeting each failure mode.

## Non-goals / Non-deliverables

- Refactoring the in-memory cosmos network integration beyond the scope of this issue's goals.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**:

**Comment by Olshansk** [comment]
Looks like we'll have to deal with some race conditions...

**Comment by Olshansk** [comment]
Tests have undergone many iterations so this is stale.
