### ISSUE TITLE
[Testing] Subscription to events using an in-memory network

### ISSUE THREAD

**Issue by h5law** [pokt-network/poktroll#303]
## Objective

To discover how events (such as new blocks and redelegation events) can be subscribed to using an in-memory network. Utilising this knowledge implement the usage of in-memory networks in both the block client [1] and delegation client [2] integration tests.

[1] https://github.com/pokt-network/poktroll/blob/main/pkg/client/block/client_integration_test.go
[2] https://github.com/pokt-network/poktroll/blob/main/pkg/client/delegation/client_integration_test.go

## Origin Document

We have the ability to create in-memory networks [1], these are already being used in numerous tests (CLI tests AFAIK). However the `BlockClient` integration test [2] **requires** localnet to be running (which is not ideal). The `DelegationClient` integration test [3] attempts to use an in-memory network but is:

1. Outdated and does not utilise the changes @bryanchriswhite has made
2. Unable to subscribe successfully to events on this in-memory network

This leads us to the reason for why this issue is **required**. We **need** to be able to test subscription to events using real components while also mocking the network (aka using the in-memory network) for integration tests.

[1] https://github.com/pokt-network/poktroll/blob/main/testutil/network/network.go
[2] https://github.com/pokt-network/poktroll/blob/main/pkg/client/block/client_integration_test.go
[3] https://github.com/pokt-network/poktroll/blob/main/pkg/client/delegation/client_integration_test.go

## Goals

- Figure out how subscriptions work on the in-memory network
- Discover how to subscribe to events using the in-memory network in [1]

[1] https://github.com/pokt-network/poktroll/blob/main/testutil/network/network.go

## Deliverables

- [ ] Make any changes necessary to the in-memory network [1] to allow for event subscription
- [ ] Figure out the correct web-socket URL to use for the `EventsQueryClient`.
- [ ] Update the block client integration test [2] to no longer use localnet but the in-memory network [1] and subscribe for new block events.
- [ ] Update the delegation client integration test [3] to use [1] and subscribe to re-delegation events.

[1] https://github.com/pokt-network/poktroll/blob/main/testutil/network/network.go
[2] https://github.com/pokt-network/poktroll/blob/main/pkg/client/block/client_integration_test.go
[3] https://github.com/pokt-network/poktroll/blob/main/pkg/client/delegation/client_integration_test.go

## Non-goals / Non-deliverables

- Break any existing tests that utilise the in-memory network

[1] https://github.com/pokt-network/poktroll/blob/main/testutil/network/network.go

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @h5law 
**Co-Owners**: @bryanchriswhite

**Comment by Olshansk** [comment]
@bryanchriswhite Is this ticket still relevant in your opinion?

**Comment by bryanchriswhite** [comment]
@Olshansk TL;DR, I don't think it's a priority but I could imagine that it comes up again at some point in the future.

AFAIK, we still don't know how to do this and this issue contains a lot of good context to make progress if we needed to at any point. As it stands, this is only a blocker for a few E2E tests which are currently skipped.

**Comment by Olshansk** [comment]
Keeping open. Removing iteration. Adding `potential community` label.

**Comment by Olshansk** [comment]
@bryanchriswhite Can you close this out if it's no longer relevant please
