### ISSUE TITLE
[DRAFT][Portal] Deploy Portal on DevNet

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#308]
## Objective

[ What? Describe the issue in 1-2 sentences]

## Origin Document

[ Why? Justify the issue in 1-2 sentences. Consider adding a link or a screenshot.]

## Goals

- Goal #1
- Goal #2
- ...

## Deliverables

- [ ] Document where DevNet is, how to access and where to get visibility it
- [ ] Update infrastructure so Portal can be deployed to DevNet
- [ ] Add utilities to run relay (i.e. curl command) through Portal on DevNet

## Non-goals / Non-deliverables

- Non-goal #1
- Non-deliverable #2
- ...

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @ezeike

**Comment by ezeike** [comment]
Portal (gateway) deploy on devnet on hold until gateway's shannon support is deployed into prod.

@Olshansk Are we still going to connect our gateway to a shannon devnet?

**Comment by Olshansk** [comment]
> Portal (gateway) deploy on devnet on hold until gateway's shannon support is deployed into prod.

Where can we track this?

> @Olshansk Are we still going to connect our gateway to a shannon devnet?

Shannon TestNet. https://testnet-validated-validator-rpc.poktroll.com/

**Comment by Olshansk** [comment]
@ezeike Bump on ☝️

**Comment by Olshansk** [comment]
No longer relevant.
