### ISSUE TITLE
[On-Chain] Allow keepers to access previous blocks info

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#310]
## Objective

The  `Session` keeper implementation needs to have access to past blocks hash to derive its `SessionId` but we currently have no way besides the workaround implemented in the alpha repo [1][2].

Additionally, `Claim` creation may also need it to derive the earliest claim creation block height.

[1] https://github.com/pokt-network/poktroll-alpha/blob/main/x/servicer/keeper/msg_server_claim.go#L35
[2] https://github.com/pokt-network/poktroll-alpha/blob/main/x/servicer/keeper/msg_server_proof.go#L41

## Origin Document

There's is currently a `TODO_BLOCKER` on the `Session` keeper that captures the issue [1]

![image](https://github.com/pokt-network/poktroll/assets/231488/ccd2d497-e269-41ea-a889-42b32961291c) 

[1] https://github.com/pokt-network/poktroll/blob/main/x/session/keeper/session_hydrator.go#L107

## Goals

- Investigate how to get any past block hash given its height.
- Try to avoid using a network client to get that info.
- Document the solution and how to use it in other places of the on-chain codebase.

## Deliverables

- [ ] A PR implementing a `GetBlockHashByHeight` function that uses the Cosmos SDK that could be used by the keepers.
- [ ] If unsuccessful, document the investigation on a notion document and implement the network client workaround.

## Non-goals / Non-deliverables

- Implement a keeper for keeping track of past blocks hashes

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @red-0ne 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
Great desription @red-0ne!

**Comment by red-0ne** [comment]
@Olshansk I believe we can go with this solution if we don't manage to properly query the Tendermint node. What worries me here, is that we won't be able to query blocks past the circular buffer which makes the `GetSession` non-deterministic (something we want to avoid for on-chain queries).

I would rank this solution above the Tendermint network client anyway.

**Comment by red-0ne** [comment]
Opting for @Olshansk 's solution
