### ISSUE TITLE
[Governance] Align on how we want to manage Governance Parameter Updates

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#322]
## Objective

Design & document how governance parameters should be designed, updated, and maintained. In doing so, determine how they should be governed both in the short & long term.

## Origin Document

In Morse (v0), we `rolled our own` on-chain parameter governance. With Shannon (v1), we are aiming to follow best Cosmos SDK practices to stay up to sync with the latest maintain and build on top of efforts from the community.

### Morse (v0)

In Morse:
1. We use the now deprecated Cosmos `x/params` module. All parameters live in one place and are namespaced.
2. Leverage a custom-built [multi-sig](https://github.com/pokt-network/pocket-core/blob/69a035dda4566d6b49bba04bb2090495d22f3683/doc/specs/cli/accounts.md?plain=1#L312) library.
3. Created the [pocket tx change_param](https://github.com/pokt-network/pocket-core/blob/69a035dda4566d6b49bba04bb2090495d22f3683/app/cmd/cli/gov.go#L124) CLI command to execute the results of [voted on proposals](https://gov.pokt.network/#/) based on discussions in [forum.pokt.network](https://forum.pokt.network/).

### Shannon (v1)

In the Cosmos SDK, given that [ADR 46](https://docs.cosmos.network/main/build/architecture/adr-046-module-params) has passed, every module now maintains it's own params and [x/params](https://docs.cosmos.network/main/build/modules/params) is deprecated.

Below is a code snippet taken from [cosmos/mint/v1beta1/tx.proto](https://github.com/cosmos/cosmos-sdk/blob/b44317ebce26aaf288b81387c65586a1784e3c6a/proto/cosmos/mint/v1beta1/tx.proto#L26) w/ the new standard of how params should be updated:

```proto
// Msg defines the x/mint Msg service.
service Msg {
  option (cosmos.msg.v1.service) = true;

  // UpdateParams defines a governance operation for updating the x/mint module
  // parameters. The authority is defaults to the x/gov module account.
  //
  // Since: cosmos-sdk 0.47
  rpc UpdateParams(MsgUpdateParams) returns (MsgUpdateParamsResponse);
}

// MsgUpdateParams is the Msg/UpdateParams request type.
//
// Since: cosmos-sdk 0.47
message MsgUpdateParams {
  option (cosmos.msg.v1.signer) = "authority";
  option (amino.name)           = "cosmos-sdk/x/mint/MsgUpdateParams";

  // authority is the address that controls the module (defaults to x/gov unless overwritten).
  string authority = 1 [(cosmos_proto.scalar) = "cosmos.AddressString"];

  // params defines the x/mint parameters to update.
  //
  // NOTE: All parameters must be supplied.
  Params params = 2 [(gogoproto.nullable) = false, (amino.dont_omitempty) = true];
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
//
// Since: cosmos-sdk 0.47
message MsgUpdateParamsResponse {}
```

A few things to note here:
1. The `authority` address is used to determine who can updates params
2. There is a note next to the  implementation requiring that `All parameters must be supplied`
3. There is no CLI entrypoint to update these as everything is done through on-chain proposals via [x/gov](https://docs.cosmos.network/main/build/modules/gov)

Until Shannon is mature enough to transition to complete on-chain governance via proposals as described in `x/gov`, we need to use PNF to maintain the address to manage these params.

In practice, this potentially means using the `x/authz` module to delegate from `authtypes.NewModuleAddress(govtypes.ModuleName).String()` to some address maintained by the foundation (e.g. `foundationAddress`).

For example, the following will is an example for the tokenomics parameters:

```go
authority := authtypes.NewModuleAddress(govtypes.ModuleName).String()
foundationAddress := "xxx"
tokenomicsUpdateParam := &tokenomicsmoduletypes.MsgUpdateParams{}
  // repeat this for every `MsgUpdatePrams` method
authorization := authz.NewGenericAuthorization(proto.MessageName(tokenomicsUpdateParam))
grant, err := authz.NewGrant(time.Now(), authorization, nil)
if err != nil {
	panic(err)
}
grantMsg := &authz.MsgGrant{
	Granter: authority,
	Grantee: daoAccount,
	Grant:   grant,
}
// grantMsg needs to be included in genesis
```

## Goals

- Understand the best-practices of how other projects maintain on-chain governance parameters
- Make it easy to view, manage and maintain an amalgamation of different governance params
- Study what we can leverage from `x/gov`, `x/upgrade`, `x/auth` and `x/authz`
- Provide the tooling & documentation needed to interact with these params for testing & production purposes
- Determine what parameter governance solution we want to deploy TestNet & MainNet with

## Deliverables

- [ ] Document (a playbook) on how to manage & maintain on-chain governance params with the selected solution
- [x] A PR that delegates parameter update authorization from the `gov` module to the `PNF` owned address
- [ ] An investigation into updating PRs that involves:
	- [ ] Understanding why other Cosmos SDK apps don't have a CLI for this
	- [x] If we keep our CLI, a PR that makes it possible to update one parameter at a time
- [ ] Create follow-up work / tickets that captures some of the non-goals below

## Non-goals / Non-deliverables

- Adding parameter update code flows to all modules
- A documents (i.e. a playbook) that explain how to use `x/gov` & `x/upgrade` in MainNet

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk

**Comment by Olshansk** [comment]
In terms of next steps, what I'm going to do is reach out to someone in the Cosmos ecosystem that has experience with `Protocol upgrades` & `Governance params` to get feedback on potential next steps from their experience.

**Comment by h5law** [comment]
Note to self: @h5law update max delegated gateways to follow this pattern

**Comment by Olshansk** [comment]
Capturing a tl;dr list of questions (without links to keep things simple) that we need to get feedback on.

1. Is there an "accepted" multisig library we should be using with the Cosmos SDK as an ABCI application? _Note: Threshold signing is not necessary, just multiple signatures tied to one address._
2. Is there an on-chain feature flag system? _For example, enable a code-path or change a value at a specific height._
3. What is the "accepted" way to have a trusted on-chain address (see 1) to drive state changes (see 2)?

**Comment by Olshansk** [comment]
I'm closing this out because we have a plan and it's a matter of transitioning everything over nwo.
