### ISSUE TITLE
[LocalNet] Fix sequencer hot reloading

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#325]
## Objective

Hot-reloading (quick restart after the code is updated) currently doesn't work.

## Origin Document

Conversation starting from [this](https://github.com/pokt-network/poktroll/pull/277#issuecomment-1886073173) comment.

We are using [helm_resource](https://github.com/tilt-dev/tilt-extensions/tree/master/helm_resource) extension for Tilt which doesn't seem to work well with Hot Reloading ([more info](https://github.com/tilt-dev/tilt-extensions/issues/391)). We've had a similar set-up work in another repo, but it was using Tilt's `helm()` function - [example](https://github.com/pokt-network/pocket/blob/main/build/localnet/Tiltfile). We can switch to that implementation for `poktroll` repo as well.

## Goals

- Sequencer process restarts automatically after code is changed.

## Deliverables

- [ ] Switch to [Tilt's `helm()`](https://docs.tilt.dev/api#api.helm) instead of `helm_resource` extension.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: [GitHub handle of issue owner]
**Co-Owners**: [OPTIONAL - GitHub handle of co-owner(s)]

**Comment by Olshansk** [comment]
Duplicated of #399.
