### ISSUE TITLE
[TestNet] Spin up new TestNet

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#340]
## Objective

After success with previous TestNet, let's bring another one online. This time, we will maintain fresh versions of the sequencer and will allow others to participate.

## Goals

- A sequencer running on Mocha Testnet
- A sequencer accepts connections from the internet for p2p

## Deliverables

- [x] Deploy new TestNet, exposed to the internet
- [ ] Updated documentation in the [notion doc](https://www.notion.so/buildwithgrove/Testnet-3f2f461ba5254eaca0bb3a9a31f8fc32?pvs=4) on things like:
	- How to observe / validate the testnet
	- How to manually deploy it
	- Anything else necessary for other members of the team to repeat the process

## Non-goals / Non-deliverables

- Don't build automation to upgrade version on TestNet, we'll deploy the sequencer manually first

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @okdas 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@okdas Added one more deliverable related to documentation surrounding this task.

**Comment by okdas** [comment]
We do have what seems to be the stable network on Rollkit now. I'm keeping the ticket open as a reminder to write the docs on how to deploy another network. Just in case somebody else might want to do it. Some notes are already available in [Notion](https://www.notion.so/buildwithgrove/Testnet-3f2f461ba5254eaca0bb3a9a31f8fc32?pvs=4).

**Comment by Olshansk** [comment]
@okdas While you're working on the documentation in the background. Do you mind also posting a few links here for others (node runners, community members, celestia, etc...) to have visibility into the up and running sequencer?

**Comment by okdas** [comment]
@Olshansk I added a deliverable to #25 ticket to expose the TestNet related Grafana dashboards if that is possible to do securely.

**Comment by okdas** [comment]
The documentation on how to deploy a new network is available to the team members in [Notion](https://www.notion.so/buildwithgrove/How-to-deploy-a-new-TestNet-be9b2ae477a54555bada15dfbd8cb5c8?pvs=4).
