### ISSUE TITLE
[Documentation] Document SDK usage

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#343]
## Objective

Document the current state of the `Poktroll SDK`.

## Origin Document

Ths notion page on the [Poktroll SDK](https://github.com/orgs/pokt-network/projects/144/views/8?query=is%3Aopen+sort%3Aupdated-desc)

![Screenshot 2024-01-23 at 11 23 34 AM](https://github.com/pokt-network/poktroll/assets/1892194/799f7789-01d0-41b3-b816-1fa4d710c36f)

## Goals

- Enable new suppliers to start running a supply node easily
- Enable new gateways to start running a gateway easily
- Ease the transition for ecosystem members from Morse to Shannon
- Create a foundation for the SDK documentation based off of which we can get feedback

## Deliverables

- [ ] PR with docusaurus documentation page on:
	- [ ] What is the poktroll SDK?
	- [ ] What it's intended use case is
	- [ ] How to contribute
	- [ ] Where to ask questions
	- [ ] How to use it right now
- [ ] Move over the notes from [notion](https://github.com/orgs/pokt-network/projects/144/views/8?query=is%3Aopen+sort%3Aupdated-desc) to a `.md` file

## Non-goals / Non-deliverables

- Document future steps for the SDK
- Exhaustively implement all feature parity with Morse
- Expose all on-chain functions via the SDK
- https://www.notion.so/buildwithgrove/POKTRoll-SDK-f8f320c268e14e7dabac92edb90077f5?pvs=4

## General deliverables

- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @red-0ne 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@red-0ne I have update the goals, deliverables & non-goals for this issue. Lmk if it aligns with what you were thinking.

**Comment by red-0ne** [comment]
Closing as per #349
