### ISSUE TITLE
[Code Health] Simplify error object usage

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#347]
## Objective

Simplify usage of [cosmos-sdk error objects](https://pkg.go.dev/cosmossdk.io/errors@v1.0.0#Error). Prefer calling [`#Wrap()`](https://pkg.go.dev/cosmossdk.io/errors@v1.0.0#Error.Wrap)/`[#Wrapf()`](https://pkg.go.dev/cosmossdk.io/errors@v1.0.0#Error.Wrapf) methods over using [`Wrap()`](https://pkg.go.dev/cosmossdk.io/errors@v1.0.0#Wrap)/[`Wrapf()`](https://pkg.go.dev/cosmossdk.io/errors@v1.0.0#Wrapf) static functions to improve readability.

### https://github.com/pokt-network/poktroll/pull/328#discussion_r1463916431

![image](https://github.com/pokt-network/poktroll/assets/600733/bd2298c5-65f1-45c9-abcc-c2f263e63bfd)

## Goals

- Improve readability by simplifying unnecessarily verbose error construction.

## Deliverables

- [ ] A single PR that removes all usage of the static functions referenced in the objective above where the `error` being passed is a `sdkerrors.Error`, calling it's respective method instead. 
    - The following was verified on `VSCode`, but the regex pattern likely works on other IDEs as well

```
A source code-wise find-replace using regex pattern match
// of `sdkerrors\.Wrapf\(([a-zA-Z]+), ` with `$1.Wrapf(`
```

## Non-goals / Non-deliverables

- Updating error message format/strings
- Renaming error variables
- Updating error handling logic

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @h5law

**Comment by Olshansk** [comment]
@bryanchriswhite Got a similar comment from @h5law on my PR and confirmed that we can just do a global regex find+replace.

```
// TODO_TECHDEBT: Do a source code wise find-replace using regex pattern match
// of `sdkerrors\.Wrapf\(([a-zA-Z]+), ` with `$1.Wrapf(`
```

![Screenshot 2024-01-25 at 11 22 37 AM](https://github.com/pokt-network/poktroll/assets/1892194/92d4b876-3bca-4865-b82f-ad0537f4cda3)
