### ISSUE TITLE
[COMMUNITY TESTING] On-board community deployment testers

### ISSUE THREAD

**Issue by moatus** [pokt-network/poktroll#350]
## Objective

On-board 1 to 2 community deployment testers to help deploy and troubleshoot the first versions of Shannon. These testers will run alpha versions POKT Full Nodes, connect the POKT Full Nodes to Chain nodes, and provide data/feedback to the protocol team.

## Origin Document

As protocol releases new versions and features, they need testers that can provide testing in native node runner environments. This will allow the protocol team to test deployments and test protocol features with experienced node runners.

## Goals

- Spin up alpha POKT Full Nodes
- Connect alpha nodes to chain nodes
- Provide protocol team with data and feedback to address bug and drive development goals
- Provide protocol team with direct comms to experienced node runner

## Deliverables

- [x] Organize compensation model with PNF
- [x] Secure testers
- [x] Onboard to relevant channels
- [ ] Deploy first nodes & connect to Chain Nodes

---

**Creator**: @moatus

**Comment by Olshansk** [comment]
@moatus 👌 

A few things to keep in mind. A few additional things to simply keep in mind & consider:
1. Need to figure out the comms channel where early Shannon Suppliers & Gateways can ask the protocol team questions.
2. We'll be directing them to our documentation. In particular the configs section put together by @red-0ne : https://dev.poktroll.com/category/configs
3. A few things that @okdas is working on to enable this are:
- #24 
- #340
- #342
4. A nice to have would be #27

**Comment by Olshansk** [comment]
Given that we are already capturing external feedback, marking this as completed. https://www.notion.so/buildwithgrove/TestNet-external-node-runners-feedback-0a3d634572cc41c997f1e7ecaabdca4c?pvs=4
