### ISSUE TITLE
[Testing] Unit test POKTRollSDK

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#353]
## Objective

Ensure test coverage for the `POKTRollSDK` package.

## Origin Document

`POKTRollSDK` is a critical package that ensures proper interaction with the Pocket network and used by both `Application`s and `Gateway`s.

Securing the right behavior of the SDK with the adequate tests is required to have a stable off-chain workflow.

## Goals

- Lock `POKTRollSDK` behavior with unit tests
- Deter any non-handled nil pointer references

## Deliverables

- [ ] A single PR, unit testing `POKTRollSDK` and covering all its execution paths by:
  - [ ] Adding and using the appropriate mocks.
  - [ ] Adding code instrumentation to put the SDK in the desired state.
  - [ ] Expressing the expected outcome of each tested case.

## Non-goals / Non-deliverables

- Write E2E tests.
- Test any behavior that goes beyond the SDK responsibilities.
- Have 100% test coverage.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
---

**Creator**: @red-0ne 
**Co-Owners**: @Olshansk @h5law

**Comment by Olshansk** [comment]
See #363 for future references.

**Comment by Olshansk** [comment]
@red-0ne Do you think this ticket is well documented enough to be picked up by the community?

**Comment by red-0ne** [comment]
@Olshansk , I think this should be closed in favor of another ticket on the `shannon-sdk` repo.

**Comment by Olshansk** [comment]
> @Olshansk , I think this should be closed in favor of another ticket on the `shannon-sdk` repo.

Makes sense to me. Take the lead on closing this out and linking to the new one when ready!

**Comment by red-0ne** [comment]
Closing in favor of https://github.com/pokt-network/shannon-sdk/issues/13
