### ISSUE TITLE
[bug] Goroutines leaks on RelayMiner/AppGate

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#354]
## Objective

Both AppGate and RelayMiner creating, but not cleaning up goroutines at approx 2 goroutines per relay.

## Origin Document

<img width="1467" alt="image12312" src="https://github.com/pokt-network/poktroll/assets/4950477/5306ab45-fcac-4493-af01-90b014fe3a48">

## Goals

- Make sure the amount of goroutines does not grow linearly with a number of relays. 

## How to reproduce

1. Start LocalNet: `make localnet_up`
2. Stake actors and run e2e tests to make sure LocalNet works: `make supplier1_stake && make app1_stake` && `make test_e2e`
3. Get the current numbers of goroutines:

AppGate:
```
curl localhost:9093 | grep go_goroutines
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 77
```

RelayMiner:
```
curl localhost:9094 | grep go_goroutines
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 846
```

(This number already seems kind of high after runnung e2e tests)

4. Now, run basic load test: `make load_test_simple`
5. Check the number of routines again:

AppGate:

```
curl localhost:9093 | grep go_goroutines
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 11743
```

RelayMiner:
```
curl localhost:9094 | grep go_goroutines
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 18219
```

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @okdas 
**Co-Owners**: @red-0ne @okdas

**Comment by Olshansk** [comment]
CCing @ezeike @adshmh as well. This is the first (of many) tickets where protocol & backend work will start to overlap.

**Comment by Olshansk** [comment]
@red-0ne 

> could you please run load tests again on PR https://github.com/pokt-network/poktroll/pull/410's branch with the same setup so we can compare numbers?

Do we not have a way to reproduce this locally?

I recall reviewing & updating the instructions here: https://dev.poktroll.com/infrastructure/testing/load_testing

**Comment by red-0ne** [comment]
The leaks count is request dependent, and reference numbers would not be the same as the load testing script is 100VUs x 1minute with as much requests as possible. So numbers may differ from one machine to the other.

**Comment by Olshansk** [comment]
> The leaks count is request dependent, and reference numbers would not be the same as the load testing script is 100VUs x 1minute with as much requests as possible. So numbers may differ from one machine to the other.

Got it.

My goal is not to have a specific number but understand how to reproduce it.

For example:

1. If I wanted to check/observe/see if there are any leaks on my LocalNet, which doc do I read/follow to do this?
2. If I wanted to check/observe/see if there are any leaks on my DevNet, which doc do I read/follow to do this?

**Comment by red-0ne** [comment]
> > The leaks count is request dependent, and reference numbers would not be the same as the load testing script is 100VUs x 1minute with as much requests as possible. So numbers may differ from one machine to the other.
> 
> Got it.
> 
> My goal is not to have a specific number but understand how to reproduce it.
> 
> For example:
> 
> 1. If I wanted to check/observe/see if there are any leaks on my LocalNet, which doc do I read/follow to do this?
> 2. If I wanted to check/observe/see if there are any leaks on my DevNet, which doc do I read/follow to do this?

1. Have localnet up
2. issue `curl localhost:PORT | grep go_goroutines` (9003 for appgate server, 9004 for relay miner)
3. `make send_relay`
4. do `2.` again and see the difference for a single relay.

I will document this in docusaurus. Will create a ticket to capture it.

**Comment by Olshansk** [comment]
@red-0ne posts an update next friday on how many go routine leaks we have. The goal is zero. If there is a VERY clear path to getting to zero, keep this open. If there's isn't, close it out and new tickets will be created when necessary.

**Comment by Olshansk** [comment]
@okdas Do you think we have resolved enough go-routines to close this one out?

**Comment by okdas** [comment]
@Olshansk looking at resource utilization on DevNets - we still saturate CPU when not serving requests. I'll get some pprof snapshots from these nodes so we can investigate.

**Comment by Olshansk** [comment]
Perfect, thanks for the update @okdas!

**Comment by okdas** [comment]
I think we're in a good position now with one exception we are going to work on - #551.
