### ISSUE TITLE
[Testing] Ensure unit test coverage of supplier module

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#362]
## Objective

Ensure suffiicent unit test coverage of the supplier module.

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/600733/f0989e2e-bdf8-49f3-84a5-d5ef71e97984)

## Goals

- Port applicable, existing, unmerged tests (#266, #250).
- Identify and add any important and missing coverage.

## Deliverables

- [ ] Port applicable tests from #266 
- [ ] Port applicable tests from #250

## Non-goals / Non-deliverables

- ...

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**:

**Comment by Olshansk** [comment]
TOo general.
