### ISSUE TITLE
[DASHBOARD] Shannon Dashboard Information

### ISSUE THREAD

**Issue by ezeike** [pokt-network/poktroll#383]
## Objective

Create a notion page that describes how Protocol team can examine Grove Gateway's Shannon metrics and logs.

## Origin Document

The Grove gateway has received an update designed to support the Shannon
protocol, which will allow access to the Shannon testnet upon its
deployment. By enabling the protocol team to access the gateway's metrics and
logs, we can provide critical assistance in debugging, testing, and further
development of both the Shannon protocol and Shannon testnet.

## Goals

- Give the protocol team the necessary information to access the gateway's prometheus metrics and logs.
- This information should include a short summary of the kind of information available.

## Deliverables

- [ ] Notion document with all information required to access the Grove gateway's Grafana Dashboards.

**Comment by Olshansk** [comment]
@ezeike  Do you mind using the default template we use to outline all the details? It'll require a little bit of thought on what the goals, deliverables, etc are, but will be good preparation for tackling the task.

I also think there's an opportunity to provide more detail in the PR description on what exactly you aim to achieve w/ this document.

https://github.com/pokt-network/poktroll/assets/1892194/fd39f194-6899-46c9-99e5-b725920b1aa9

**Comment by ezeike** [comment]
Shannon Grafana dashboard & instructions will be created after the gateway is using a Shannon network.

**Comment by Olshansk** [comment]
@ezeike 

> Shannon Grafana dashboard & instructions will be created after the gateway is using a Shannon network.

What is the ETA on this?

For reference, here is the link to the TestNet: https://testnet-validated-validator-rpc.poktroll.com/

**Comment by Olshansk** [comment]
@ezeike to add a link to metrics in grafana that isolate Shannon specific events.

**Comment by Olshansk** [comment]
@ezeike to add link to gateway PR that enables this.

**Comment by Olshansk** [comment]
@ezeike Can you please link to to the docs?

**Comment by Olshansk** [comment]
@ezeike Going to close this out due to lack of response and open a separate one to get it done.

**Comment by ezeike** [comment]
Information on Shannon status and Grafana access is here:

https://www.notion.so/buildwithgrove/Grove-Gateway-Shannon-Resources-f934e12f97014e1a8d754575a3fdaabd

**Comment by Olshansk** [comment]
@red-0ne CC ☝️ for if/when it's needed as a reference
