### ISSUE TITLE
[AppGate] Enable Application -> Gateway Delegation

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#39]
## Objective

Create a foundation for the `Gateway` module in the [poktroll](https://github.com/pokt-network/poktroll) repo for the Shannon upgrade.

## Origin Document

[Gateway actor in the Pocket Network Utility Specification](https://github.com/pokt-network/pocket-network-protocol/tree/main/utility#35-gateway-protocol)

## Goals

- Enable an E2E HTTP relay
- Build the foundation for the `Gateway` actor in [Pocket Network](https://pokt.network/)
- Build the foundation for the `gateway` module using the [Cosmos SDK](https://v1.cosmos.network/sdk) in Pocket
- Identify time-consuming TODOs to be done during the integration and testing stages
- Enable implementing business logic atop of a well-documented and well-tested codebase in downstream PRs

## Deliverables

- [x] A **single PR** that uses [ignite](https://ignite.com/) to scaffold the `DelegateToGateway` and `UndelegateFromGateway` messages in the `application` module
- [x] A **single PR** that adds a parameter for the maximum number of gateway
- [x] A **single PR** that adds the business logic and test utils for this functionality
- [ ] #111
- [x] Unit tests & validation across the board

## Non-goals / Non-deliverables

- Support for `unbonding` periods after undlegating
- Allow-listing or other "scope creep" like features

## General deliverables

- [x] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [x] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [x] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [x] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-owners**: @h5law

**Comment by RossiNYC** [comment]
https://hackmd.io/@blockscience/HkxbDcWZ6

**Comment by h5law** [comment]
Closing this as its done 🔥

**Comment by Olshansk** [comment]
Fuck yeah
