### ISSUE TITLE
[Code Health] Params tests don't assert initial state

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#394]
## Objective

[ What? Describe the issue in 1-2 sentences]

## Origin Document

[ Why? Justify the issue in 1-2 sentences. Consider adding a link or a screenshot.]

## Goals

- Goal #1
- Goal #2
- ...

## Deliverables

- [ ] Deliverable #1
- [ ] Deliverable #2
- ...

## Non-goals / Non-deliverables

- Non-goal #1
- Non-deliverable #2
- ...

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: [GitHub handle of issue owner]
**Co-Owners**: [OPTIONAL - GitHub handle of co-owner(s)]

**Comment by Olshansk** [comment]
@bryanchriswhite Can you please update this w/ a screenshot or reference when you have a chance?

**Comment by bryanchriswhite** [comment]
Closing as this will likely be resolved on a per-module basis as `msg_update_params_test.go` files are updated alongside changes to modules' params.
