### ISSUE TITLE
[Governance] On-Chain Governance

### ISSUE THREAD

**Issue by RossiNYC** [pokt-network/poktroll#41]
## Objective

Move some off-chain governance on-chain, automate manual triggers executed by PNF

## Origin Doc
https://www.notion.so/poktdao/Governance-Shannon-a961842036404df99dfc1712a10bdabf

## Goals

1. Enshrine on-chain governance (removing PNF as an execution oracle)
2. Have a low stakes MVP (i.e. some simple parameters that can be controlled via on-chain gov)
3. Safely do the above (have a PNF override until it feels safe)

## Deliverables
- TBD

## Non-Goals/Deliverables
- TBD

## Open Questions:
- Does Rollkit support CosmoSDK x/Gov? 
- If Not, can we extend it? 

---

Creator: @RossiNYC
Co-Owners: Ben @ PNF

**Comment by moatus** [comment]
I'll break this down into specific issues.

**Comment by Olshansk** [comment]
Closing out as no longer relevant in the short/mid term.
