### ISSUE TITLE
[Docs] Claim & Proof expiration Documentation

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#419]
## Objective

Have a clear understanding on why the protocol needs to have Proof & Claim expiration and how it works, so this can be implemented as per the requirements.

First hints as to **why** it is needed on a permissionless network:
  - Lots of claims for “small sessions”
  - Proof are large → bloat the network

Hints on **how** this will be done:
- Proof (claim?) Window closes
  - If proof IS required AND proof is provided → validated and reward
  - If proof IS NOT required → reward

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/231488/5693ba4d-c156-4197-b0df-f56171e16cd3)

## Goals

- Document how `Claim` expiration works and how it is related to its corresponding `Proof`.
- Document why and in which cases this is needed.
- Have a clear document that could be used as a reference for a future implementation of the mechanism

## Deliverables

- [x] A docusaurus documentation PR explaining `Claim` expiration, its relation to its corresponding proof and why this is needed.
  - #649 

## Non-goals / Non-deliverables

- Implementation of the described mechanism

**Creator**: @Olshansk

**Comment by Olshansk** [comment]
This is awesome @red-0ne!!!!

Thank you for putting it together. I'll do it in the next iteration 🤝

**Comment by Olshansk** [comment]
Here is the reference document for probabilistic proofs: https://github.com/pokt-network/pocket-core/blob/staging/docs/proposals/probabilistic_proofs.md
