### ISSUE TITLE
[Scalability] Replace `SparseMerkleClosestProof` types with `SparseCompactMerkleProof` types

### ISSUE THREAD

**Issue by h5law** [pokt-network/poktroll#427]
## Objective

To save disk space when submitting proofs on-chain and reduce the overall blockchain size.

The above enables the long-term scalability & longevity of the blockchain.

## Origin Document

On-chain proofs comprise the majority of Pocket Network's chain.

We can use serialized/marshalled "compact" (i.e. compressed) versions of the `ClosestProof` instead of the default ones to saves space. See the following references:

- https://github.com/pokt-network/smt/blob/868237978c0b3c0e2added161b36eeb7a3dc93b0/proofs.go#L224
- https://github.com/pokt-network/smt/blob/868237978c0b3c0e2added161b36eeb7a3dc93b0/proofs.go#L260

Compact proofs can be validated directly without needing to decompact them by the caller since it is done by the SMT library:
- https://github.com/pokt-network/smt/blob/868237978c0b3c0e2added161b36eeb7a3dc93b0/proofs.go#L396
- https://github.com/pokt-network/poktroll/pull/423#discussion_r1522210094

## Goals

- Reduce the amount of space required to store a proof on-chain

## Deliverables

- [ ] Replace the occurrences of the usage of `SparseMerkleClosestProof` with its compacted form
- [ ] Enable the usage of compact proofs by making the necessary changes throughout the codebase

## Non-goals / Non-deliverables

- Improve the compacting function for the `SparseMerkleClosestProof` (see [smt/issues/41](https://github.com/pokt-network/smt/issues/41) instead)
- Change the claim/proof lifecycle outside of changing the type of proof used

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @h5law 
**Co-owner**: @Olshansk

**Comment by Olshansk** [comment]
@h5law Made some edits to the issue. PTAL and update if necessary.

**Comment by Olshansk** [comment]
@red-0ne complete this in one of our prior iterations.
