### ISSUE TITLE
[Review][Olshansky] Review, Update, Improve & Provide Feedback on Documents

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#436]
## Objective

Review various documents covering different domains across the stack

## Goals

- Help Olshansky organize all the documents that need to be reviewed in this iteration
- Make it easy for others to add additional requests by adding a deliverable in this GitHub Issue
- Review all of the documents that need feedback
- Make it easy to add additional documents 

## Deliverables

Legend

🟡 Reviewed and waiting for feedback
⚪ Not Started
🟢 Completed
🔴 Falling Behind or deprecated

### Public Docs (or docs that will be made public)
- [x] [Shannon App Client](https://www.notion.so/buildwithgrove/Shannon-App-Client-07fd0325f0d347f1acef220fdea64f0b?pvs=4) ⚪
- [x] [Shannon Overview](https://www.notion.so/buildwithgrove/Shannon-Overview-f3ca88d385194f5485aea69066bdcd07?pvs=4) ⚪
- [x] Review [Redelegation Event Delays](https://www.notion.so/buildwithgrove/Path-Reseller-API-GTM-3c29b4efaea64098ad3d04408f45e538?pvs=4) ⚪
- [x] Review [protocol infra notion doc](https://www.notion.so/buildwithgrove/Infrastructure-79b1431b70374e24b10cd9da556c7645?pvs=4) and update [protocol infra](https://github.com/pokt-network/protocol-infra) github repo 🟡 
- [x] Kickoff [this effort](https://www.notion.so/buildwithgrove/Patents-3482a26b1b954e298a09584055463455?pvs=4) 🟡 
- [x] Prepare Q2 requirements for protocol/backend crossover 🟡 
- [x] Review [RPC Session Life-cycle](https://www.notion.so/buildwithgrove/RPC-Session-Life-cycle-4bcf9f97e46540a0962cbc41f29a485d?pvs=4) 🟡  
- [x] Review [SMT Audit Report](https://drive.google.com/file/d/18ThhqhsDx7fYI6Ut06ph_nyrBPIqVBEd/view?usp=drive_link) ⚪ 
- [x] [WebSocket Design](https://miro.com/app/board/uXjVNexq5Ng=/) 🟢 
- [x] Review [strategy](https://www.notion.so/buildwithgrove/Path-Reseller-API-GTM-3c29b4efaea64098ad3d04408f45e538?pvs=4)⚪ 
- [x] Review [Quality of Service docs](https://www.notion.so/buildwithgrove/Quality-of-Service-360e70f50a4b4362a5fb1cc6fe48c9b3?pvs=4) ⚪ 
- [x] Prepare [DecAI effort](https://www.notion.so/buildwithgrove/DecAI-4728b8a5c6db44e69ad4f1df8c5352b3?pvs=4) 🟡 
- [x] Update [deck](https://docs.google.com/presentation/d/1bqOECPEqH4cUdBAzpwtqHxjRoymJhcBdc98ajCxYbWw/edit#slide=id.g2c15f31556e_0_192) 🟡 
- [x] [wPOKT Migration Plan](https://hackmd.io/EQKZRTdPSyifly3CLC1oVA) 🟡 
- [x] [Grove LLM Pilot](https://docs.google.com/document/d/1mj07Nh8EDERSob19HV_KTGr6St90sCDzdc7mttHGftg/edit#heading=h.62u60npqivqy) 🟢 
- [x] DecAI PNF G2M ⚪ 
- [x] DecAI Grove G2M ⚪ 

**Creator**: @Olshansk

**Comment by moatus** [comment]
Human readable Shannon summary and Morse differences: https://www.notion.so/buildwithgrove/Shannon-Overview-f3ca88d385194f5485aea69066bdcd07
