### ISSUE TITLE
[SDK] Method to Obtain Latest Block Prior to a Block Event

### ISSUE THREAD

**Issue by ezeike** [pokt-network/poktroll#440]
## Objective

Modify the SDK to fetch the latest block upon connection to the pocket node.

## Origin Document

In order for gateways to send relays the SDK requires the latest block height. Currently the latest block height is only available once a new block has been created and the SDK receives it through the block client.

The effect is gateways cannot send relays until a new block has been created.

## Goals

- Enable the SDK to obtain block data upon connection, rather than solely waiting for a new block.

## Deliverables

- [ ] PR containing enhancement to fetch block data on initial connection to node.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @ezeike 
**Co-Owners**: @red-0ne

**Comment by ezeike** [comment]
![image](https://github.com/pokt-network/poktroll/assets/12902351/0a417b46-5d10-41ed-8d61-c068fb75a30f)

**Comment by Olshansk** [comment]
@ezeike Reminder to also update the GitHub Issue metadata. I updated it on this one to streamline things.

![Screenshot 2024-03-19 at 8 07 53 PM](https://github.com/pokt-network/poktroll/assets/1892194/8fcffe7e-d8aa-45bd-816b-c7096ff8b84b)

**Comment by Olshansk** [comment]
Needed for gateways when block times become large. Another ~ 4-6 hours of work before finishing.

**Comment by okdas** [comment]
@red-0ne Can we also add a metric (gauge) - something like `blockchain_height`, and we update this value whenever we get information about the new block on appgateserver and relayminer?

That way, we will know what block there is from our off-chain actors' Point of View. E.g. if our off-chain actor connects to the outdated full node or something - the operator could set an alert on that and troubleshoot the issue.

**Comment by Olshansk** [comment]
Super awesome idea @okdas. + 💯
