### ISSUE TITLE
[☂️ Bug] Memory leaks: relay stress test

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#463]
f## Objective

Enumerate unique causes of memory leaks evident in the relay stress test scenario. This issue to be closed when all leaks tracked by it are resolved.

## Origin Document

-  RelayMiner go routine leak
![image](https://github.com/pokt-network/poktroll/assets/600733/236d1562-75a9-4d5f-b000-436ec1d10af6)

### Supporting documentation:
- [Debugging > Memory Leaks (notion)](https://www.notion.so/buildwithgrove/Memory-Leaks-b123cd3ac9344664aeeb45b8d4dc57be)

## Goals

- Distinguishing & tracking known memory leaks.
- Facilitating the creation of issues for unique memory leaks.

## Deliverables

- Accumulate known memory leaks in this issue's description 

## Non-goals / Non-deliverables

- Intentionally fixing listed memory leaks

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @red-0ne

**Comment by okdas** [comment]
1. #450 added some reader closures that might have been a part of the problem, I can check if the situation changed at all on main branch with this change.
2. I think the best way to troubleshoot it is to expose pprof on a separate port (configurable via the config file): https://pkg.go.dev/net/http/pprof - I can pick it up next week

**Comment by Olshansk** [comment]
> I think the best way to troubleshoot it is to expose pprof on a separate port (configurable via the config file): [pkg.go.dev/net/http/pprof](https://pkg.go.dev/net/http/pprof) - I can pick it up next week

Please add a TODO in the appropriate place (or create an issue if you think it needs one) depending on how long git'll take.

**Comment by bryanchriswhite** [comment]
Closing as memory leaks seem to have subsided (for now) as a result of continued work in load testing and complete integration. :muscle:

**Comment by Olshansk** [comment]
> ~Closing as memory leaks seem to have subsided (for now) as a result of continued work in load testing and complete integration.~ 💪
> 
> Re-purposing to include go routine leaks.

@bryanchriswhite  Sgtm, but for future go-leaks, please create new tickets. I anticipate this won't be the last one. 

Also, smaller PRs.

**Comment by okdas** [comment]
Worked on it in scope of #551.
