### ISSUE TITLE
[Ecosystem] Block Explorers, TestNet Faucet & Documentation

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#491]
## Objective

Unblock Public Shannon TestNet discoverability, usage & maintainability.

## Origin Document

- This is a follow-up to #27
- @okdas was speaking to other TestNet maintainers and share some learnings w.r.t faucets

## Goals

- Make Shannon TestNet usable by introducing a POKT faucet
- Make Shannon TestNet Block Explorers & Faucets accessible & maintainable

## Deliverables

- [ ] Introduce a Shannon TestNet faucet
	- [ ] Evaluate Cosmos SDK tools (e.g. https://github.com/ping-pub/faucet)
- [ ] Add a `TestNet` section to the top of [dev.poktroll.com](https://dev.poktroll.com) that has the following subsections:
	- [ ] Maintenance (internal)
	- [ ] Usage (external) 
	- For both Maintenance & Usage, make sure to cover
		- [ ] Block Explorer
		- [ ] Faucet

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas @moatus

**Comment by Olshansk** [comment]
@moatus Please review this ticket and lmk if you have any questions.

@okdas Feel free to edit / add any additional details.

**Comment by moatus** [comment]
Faucet Repo: https://github.com/Eastman-Enterprises/Faucet

**Comment by Olshansk** [comment]
@moatus Thoughts on moving this to https://github.com/pokt-network/?

**Comment by Olshansk** [comment]
@breezytm Do you mind posting the relevant resources (repos, results, etc) here when you have a chance for posterity?
