### ISSUE TITLE
[Infra] Binaries & builds for every actor

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#495]
## Objective

Streamline building a binary / image for every actor / tool in the Shannon repo.

## Goals

- Avoiding needing to build everything from source
- Enable onboarding users 

## Deliverables

- [ ] Align on a name for each binary below
	- [ ] 	If anything changes, update docs & source code
- [x] Implement the infrastructure to automatically publish the following images from main:
	- [x] 	`poktrolld` binary
	- [x] `RelayMiner` docker image
	- [x] `AppGate Server` docker image
	- [x] `Validator` docker image
- [ ] Allow installation of `poktrolld` (or new name) via `homebrew` and `tea`
- [ ] Document the following:
	- [ ] Determine where / when a new page is necessary and when an existing docs page needs to be updated
	- [ ] **Internal tooling**:
	- [ ] **CLI users**:
	- [ ] **Operators**:
- [x] Publish an official release in the poktroll repo
- [x] Review the learnings / suggestion from this PR in Morse: https://github.com/pokt-network/pocket-core/pull/1603

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas

**Comment by Olshansk** [comment]
@okdas We got the `poktrolld` [binary](https://github.com/pokt-network/poktroll/releases/tag/v0.0.1) but images are still a WIP, right?

**Comment by okdas** [comment]
> @okdas We got the `poktrolld` [binary](https://github.com/pokt-network/poktroll/releases/tag/v0.0.1) but images are still a WIP, right?

Both image and binary are good to go, just need to write the docs on how to access and use them (#525). I'm going to close this issue as done. The other nice thing to have is a homebrew formula. I think this is a good community ticket potentially, would you agree?

**Comment by Olshansk** [comment]
> The other nice thing to have is a homebrew formula. I think this is a good community ticket potentially, would you agree?

100%. Let's outsource it. Include both homebrew and tea.xyz
