### ISSUE TITLE
[SDK] Add `REST` Support

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#511]
## Objective

Add support for `REST` requests in the `poktroll` repo so we can enable LLM relays.

## Origin Document

- https://github.com/pokt-network/poktroll/issues/130
- https://github.com/pokt-network/poktroll/pull/508#issuecomment-2080263171

![Screenshot 2024-04-29 at 11 31 27 AM](https://github.com/pokt-network/poktroll/assets/1892194/dd3f52ff-080d-45c4-adce-031bcc0cbb47)

## Goals

- Add `REST` support in the existing packages
- Enable LLM relays to flow through the network
- Refactor/cleanup / document things (if needed) to prepare for other `rpc_type`s

## Deliverables

- [ ] Implement `REST` support
- [ ] Document `REST` support (update docusarus)
- [ ] Turn on LLM relays
- [ ] Add an E2E test for an LLM relay

## Non-goals / Non-deliverables

- Adding support for all RPC types
- Handling all error edge cases exhaustively

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @red-0ne

**Comment by red-0ne** [comment]
Closed with #594
