### ISSUE TITLE
[Load Testing] TestNet load test preparation

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#533]
## Objective

Support load testing against TestNet.

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/600733/7b794ce3-9898-431a-93b3-3416c1d40519)

## Goals

- Enable relay stress load testing against testnet by running `make test_load_relays_stress_testnet`

## Deliverables

- [x] A PR which adds support to skip scaling
- [ ] A PR which adds:
  - a testnet manifest, based on `loadtest_manifest.yaml`
  - the `test_load_relays_stress_testnet` make target

## Non-goals / Non-deliverables

- Refactoring the relay stress test beyond what is necessary to achieve the goals

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @red-0ne

**Comment by okdas** [comment]
Here's a plan we've come up with:

- **Step 1: Load test our own gateway(s) and our own supplier(s)**
    - We deploy our own off-chain actors on a dedicated service ID. I'm thinking of two service IDs - Anvil and some static HTML page.
    - We test how our off-chain actors deploy in a production environment behind load balancers and external TLS termination.
    - We run load tests against our own workloads only.
    - We gather data during the whole relay lifecycle: metrics from the load balancer, gateway, supplier, on-chain data, and load tests.

- **Step 2: Load test our gateway(s) against external suppliers**
    - We run the test when more 0021 suppliers are available on the network.
    - We lose some visibility as we won't be able to get metrics from the supplier.

- **Step 3: Load test external gateways and external suppliers**
    - We run the test when more gateways are staked on the network.
    - We lose more visibility: into load balancer and gateway metrics, but we test a larger network.

- **Step 4 and further:**
    - As the network becomes more populated, we can start executing the tests from different regions.
