### ISSUE TITLE
[CLI] Integrate with Homebrew & pkgx

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#535]
## Objective

Integrate Pocket Network's binary into Homebrew for easier installation and management on macOS.

## Origin Document

The integration will streamline the installation process for users and developers, making it simpler to manage dependencies and updates.

The [CI job that provisions release binaries](https://github.com/pokt-network/poktroll/blob/main/.github/workflows/release-artifacts.yml) might be a good starting point.

## Goals

- Ensure Pocket Network's binary is accessible through Homebrew.
- Provide clear documentation for users on how to install and use the binary via Homebrew.
- Maintain compatibility with the latest version of Homebrew.

## Deliverables

- [ ] Submit a formula to the Homebrew repository for Pocket Network's binary.
- [ ] Ensure the formula passes all Homebrew CI checks.
- [ ] Update binary install documentation to provide a new way of installing the binary.
- [ ] Test the installation process on various macOS versions to ensure compatibility.

## Non-goals / Non-deliverables

- This ticket does not include the maintenance of the Homebrew formula post-integration.
- This ticket does not cover integration with other package managers.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

### Estimated Days of Work

**1 day**

_Disclaimer_: This is the total projected number of estimated hours to completion & merge. The owner of this tickets is expected to use this GitHub issue to communicate with the core protocol team along the way, with update & feedback for each deliverable throughout the duration of this work._

---

**Creator**: @okdas
**Co-Owners**: TBD

**Comment by Olshansk** [comment]
Done: https://github.com/pokt-network/homebrew-poktroll/
