### ISSUE TITLE
[Relay Mining] Introduce & Test Relay Mining Difficulty

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#542]
## Objective

Implement on-chain relay mining difficulty.

## Origin Document

Relay Mining paper - https://arxiv.org/abs/2305.10672

## Goals

- Implement the core utility of Relay Mining
- Unpack any potential issues or oversights we might have in the design or implementation

## Deliverables

- [ ] Introduce a new on-chain difficulty parameter
- [ ] Track the volume on-chain and adjust the parameter appropriately
- [ ] At least one of each of the following:
	- [ ] Unit test
	- [ ] Integration test
	- [ ] E2E test
- [ ] A new dashboard in grafana dedicated to relay mining that shows (at a minimum):
	- [ ] Number of relays
	- [ ] Relay mining difficulty
	- [ ] Change in difficulty
- [ ] A `Makefile` target to stress test LocalNet and inspect the difficulty increasing / decreasing as needed
- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.

## Non-goals / Non-deliverables

- Changes/optimizations in the algorithm
- Changes/optimizations in the SMT
- Load or stress testing the issue

---

**Creator**: @Olshansk 
**Co-Owners**: @RawthiL

**Comment by RawthiL** [comment]
Just to be clear, estimation of volume and difficulty tracking should be done per-service, ie. each service will have a pair of values, the total traffic and its difficulty.

**Comment by Olshansk** [comment]
> Just to be clear, estimation of volume and difficulty tracking should be done per-service, ie. each service will have a pair of values, the total traffic and its difficulty.

Aligned.

Work has been started in #548 and #549.
