### ISSUE TITLE
[SDK] Integrate `shannon-sdk` w/ Nodie's gateway-server

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#583]
## Objective

Integrate `shannon-sdk` into `portal-middleware`

## Origin Document

- The first independent iteration of the `shannon-sdk` is available here: https://github.com/pokt-network/shannon-sdk/pull/1
- It's first usage in `poktroll` is found here: https://github.com/pokt-network/poktroll/pull/554
- The first ieration of the documentation can be found here: https://dev.poktroll.com/develop/packages/sdk

## Goals

- Collect feedback on the new design of the Shannon SDK
- Put the foundation in place for future iterations towards Shannon

## Deliverables

- [ ] Update https://github.com/pokt-network/gateway-server using `shannon-sdk`
- [ ] Enable the usage of Shannon & Morse simulatenously
- [ ] Test an E2E Relay
- [ ] Come back with feedback on how the SDK should be updated or improved

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @red-0ne @studna

**Comment by wtfsayo** [comment]
is this something I could take up independently @Olshansk ?

**Comment by Olshansk** [comment]
@wtfsayo This hasn't been started and definitely a great onboarding task.

Please share any feedback you have on the [shannon SDK](https://github.com/pokt-network/shannon-sdk) either here or on [discord](https://discord.com/channels/553741558869131266/1234943674903953529) along the way!

Welcome aboard 🚢 

cc @adshmh @red-0ne @fredteumer for visibility.

**Comment by Olshansk** [comment]
The team at Grove spoke w/ Nodies and agreed to deprecated `gateway-server` in exchange for doubling down on `PATH`. 

Closing this out.
