### ISSUE TITLE
[Utility] Minimum staking values for each actor

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#612]
## Objective

Introduce a minimum stake (MinStake) requirement for `Gateways`, `Suppliers`, and `Applications` in the network.

## Status

- #808 
- #809 
- #843
- #844
- #845
- #847
- #848 
- #849
- #850
- #857
- ~~_TODO: [Supplier] Enforce minimum stake when slashing_~~ (added in #795; see [x/tokenomics/keeper/settle_pending_claims.go](https://github.com/pokt-network/poktroll/pull/795/files#diff-162fd3e506083088104ff9c7fa152d635766e18a54bc633b6723a0c6e88e98e7R326))
- #862

### Related

- #839 
- #851 
- #852 
- #861

## Origin Document

In Morse, if you run:

```bash
	curl --location -X 'POST' -H 'Content-Type: application/json' "${POCKET_ENDPOINT}/v1/query/allParams" | jq
```

We find the following param under `node_params`

```bash
    {
      "param_key": "pos/StakeMinimum",
      "param_value": "15000000000"
    },
```

## Goals

- Establish a clear MinStake requirement for `Gateways`, `Suppliers` & `Applications`
- Enhance network security and reliability by having "something at stake"
- Create AT LEAST Morse feature parity

## Deliverables

- [ ] Add the `MinStakeGateway` governance parameter
- [ ] Add the `MinStakeApplication` governance parameter
- [ ] Add the `MinStakeSupplier` governance parameter
- [ ] Update docusouras documentation on these params
- [ ] Add at least one minimum E2E and unit test for each
- [ ] Communicate the changes to the network participants.

## Non-goals / Non-deliverables

- Implementing any staking-related penalties or rewards beyond the initial MinStake requirements.
- Making changes to the staking mechanisms unrelated to the MinStake values.
- Addressing any other network roles not specified in this issue (e.g., Validators).

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite to ensure MinStake enforcement.
- [ ] **Makefile**: Add new targets to the Makefile to facilitate testing and deployment of MinStake functionality.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite

**Comment by bryanchriswhite** [comment]
I started [a notion doc](https://buildwithgrove.notion.site/Actor-minimum-stakes-1c57d61cd0c64745b806c885426e64a8?pvs=4) to plan this work out. @Olshansk PTAL and provide any feedback there.

**Comment by Olshansk** [comment]
> I started [a notion doc](https://buildwithgrove.notion.site/Actor-minimum-stakes-1c57d61cd0c64745b806c885426e64a8?pvs=4) to plan this work out. @Olshansk PTAL and provide any feedback there.

@bryanchriswhite Document reviewed and LGTM. Left a bunch of 👍 and a bit of feedback, but nothing blocking!

**Comment by bryanchriswhite** [comment]
Code complete as of #857; outstanding PRs are docs updates.
