### ISSUE TITLE
[Governance] Upgrade playbook and downstream investigation

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#625]
## Objective

Write the playbook on how we'll handle on-chain governance updates.

## Origin Document

- Cosmos upgrade module: https://docs.cosmos.network/v0.50/build/modules/upgrade
- Morse RC-0.11 Release Plan: https://buildwithgrove.notion.site/RC-0-11-0-Release-Plan-6b33e7b7634f458796b1c3f0a3a2a994?pvs=4
- Related to #622 but solely for on-chain purposes 

## Goals

- `Research and understand` the tools available in the Cosmos SDK for governance upgrades (i.e. `x/upgrade`)
- `Identify missing gaps` or differences between how we'll handle governance upgrades 
- `Collaborate with` the team at Informal Systems (CometBFT) or Binary Builders (Cosmos SDK) if need be

## Deliverables

- [ ] Manage a real consensus-breaking governance upgrade on TestNet
- [ ] A copy-paste template + playbook + instructionsfor every governance upgrade
- [ ] Answer the following questions:
	- [x] How do we handle consensus-breaking changes?
	- [x] How do we increase the block size like in Morse? (e.g. increase the block size)
	- [x] How do we activate a new feature at a specific height? (i.e. boolean feature switch)
	- [ ] Document protocol updates and governance upgrades

## Non-goals / Non-deliverables

- Implementing new features (e.g. features switches) if the need arises
- Achieving complete parity with how Morse work

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas

**Comment by okdas** [comment]
The functionality and code examples are in #702, with more documentation incoming in #719

**Comment by okdas** [comment]
Both PRs are now merged. We're going to continue adding/chainging the process as we issue upgrades in Beta testnet.
