### ISSUE TITLE
[Telemetry] Relay Mining Telemtry

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#626]
## Objective

Add Relay Mining Telemetry 

## Origin Document

- See the screenshot from this #610

<img width="806" alt="Screenshot 2024-06-19 at 10 20 30 PM" src="https://github.com/pokt-network/poktroll/assets/1892194/2201cfa4-747b-4cc6-ae7f-6271816289df">

## Goals

- Provide visibility into how parameters are changing during Relay Mining stress / load testing

## Deliverables

- [ ] A single PR that adds the requirements in the screenshot above to the stress testing dashboard in grafana

## Non-goals / Non-deliverables

- Any business logic changes

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @red-0ne

**Comment by red-0ne** [comment]
Closed as per #631
