### ISSUE TITLE
Unable to get localnet up or run e2e tests

### ISSUE THREAD

**Issue by rBurgett** [pokt-network/poktroll#630]
## Objective

To get the localnet up and the e2e tests running.

## Origin Document

Following the [quickstart guide](https://dev.poktroll.com/develop/developer_guide/quickstart), I cannot get a localnet up. I have tried on my own to debug it, but there are so many moving parts that I have not yet been able to figure anything out. I have the dependencies installed and can run `make go_develop_and_test` and successfully run the tests. But, when I do `make localnet_up` and open the tilt UI, almost everything says `Update Pending` and never starts up like in the video. There is one error listed in the logs:

```
ERROR: Cluster status error: Tilt encountered an error connecting to your Kubernetes cluster:
	Get "https://127.0.0.1:37189/version?timeout=32s": dial tcp 127.0.0.1:37189: connect: connection refused
```
If I open the tilt UI and look, it shows:
![signal-2024-06-20-192550_002](https://github.com/pokt-network/poktroll/assets/8548835/5b0e4a84-c1de-4cd9-8ed6-3155f81976d3)
The item with the error is called `protocol-dashboards-label`. All the other items are either good or forever updating.

I just wanted to run the e2e tests, but there is extremely little information on running them. My hope is that after getting a localnet up, I will be able to figure out how to run the e2e tests since `make test_e2e` just says,

```
post failed: Post "http://127.0.0.1:36657": dial tcp 127.0.0.1:36657: connect: connection refused
Messages:   	error getting application list
```

The quickstart guide does not say anything about what is required in order run the e2e tests, but at the moment I am assuming that I need a localnet up before I can run them.

Any help would be appreciated.

**Creator**: rburgett

**Comment by Olshansk** [comment]
@okdas This looks like it'll need a debug session. Do you mind coordinating a time to meet with Ryan and helping him out?

**Comment by Olshansk** [comment]
@rBurgett Do you mind leaving an emoji on [1]. Trying to aggregate user feedback and get a signal into how easy/hard this is.

[1] https://discord.com/channels/553741558869131266/1234943674903953529/1253478922486546524

**Comment by okdas** [comment]
> Do you mind coordinating a time to meet with Ryan and helping him out?

Sure thing!

@rBurgett quick question though before we do a debug session - what's your OS, Docker version and how do you run Kubernetes? In the docs, we recommend using [kind](https://kind.sigs.k8s.io/).

**Comment by rBurgett** [comment]
@okdas I am in Linux (an Ubuntu derivative), Docker `26.1.4`, and I am new to Kubernetes (despite having used docker heavily for many years). I installed kind as per the quickstart instructions then created and selected the cluster as per the instructions.

**Comment by okdas** [comment]
@rBurgett thanks! I deployed the stack on an Ubuntu VM using the documentation and didn't encounter issues. It seems the port is not being exposed by Docker or is unreachable from the userspace. Can you confirm your Discord username? Mine is `kdas`. Thanks!

**Comment by rBurgett** [comment]
@okdas I am amishbatman on Discord.

**Comment by okdas** [comment]
@rBurgett, could you please close this GitHub issue if the problem has been resolved on your end? Thank you!

**Comment by rBurgett** [comment]
I believe it has been. Thank you for your help.

**Comment by Olshansk** [comment]
@rBurgett Do you mind sharing 1-2 sentences on what the issue was?
