### ISSUE TITLE
[Observability] Add relays counter

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#643]
## Objective

Track the number of on-chain relays in addition to claims and compute units as they move through the claim/proof lifecycle (e.g. claimed, proven, expired, settled). 

## Origin Document

![Screenshot_20240630_090229_com brave browser](https://github.com/pokt-network/poktroll/assets/600733/2526d6f7-f3dc-49bf-b904-b28cb8910a99)

## Goals

- Expose the number of relays in each lifecycle stage via observability. 

## Deliverables

- [x] A PR that adds telemetry counter calls where appropriate; i.e. claim/proof upsert/settlement/expiration. 
- [x] A PR that updates relevant dashboards. 

## Non-goals / Non-deliverables

- Introducing additional metrics or labels
- Refactoring the telemetry pkg

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @red-0ne

**Comment by Olshansk** [comment]
@bryanchriswhite Did you not do this in another PR already or is this still a remaining open item?

**Comment by bryanchriswhite** [comment]
> @bryanchriswhite Did you not do this in another PR already or is this still a remaining open item?

This is done in #644 which is still in review.
