### ISSUE TITLE
[Infra] GitHub PR links for E2E observability don't work

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#652]
## Objective

https://github.com/pokt-network/poktroll/assets/1892194/1647d72a-da2e-4c97-ae86-28ad234e2f62

## Origin Document

https://github.com/pokt-network/poktroll/pull/650

## Goals

- Improve developer experience by being able to easily analyze errors in E2E tests...

## Deliverables

- [ ] Fix the link to GCP (visually and hyperlink)
- [ ] Fix the link to Grafana (visually and hyperlink)

## Non-goals / Non-deliverables

- Non-goal #1

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas

**Comment by okdas** [comment]
[Fixed here](https://github.com/dessant/label-actions/pull/29#issuecomment-2266237370)
