### ISSUE TITLE
[Code Health] Mitigate import cycles in pkg/client

### ISSUE THREAD

**Issue by bryanchriswhite** [pokt-network/poktroll#664]
## Objective

Mitigate looming dependency cycles in `pkg/client`.

## Origin Document

![image](https://github.com/pokt-network/poktroll/assets/600733/406016c7-0028-401a-aee9-a67da9f4d81c)
> See: https://github.com/pokt-network/poktroll/pull/655#discussion_r1666476343.

![image](https://github.com/pokt-network/poktroll/assets/600733/2bd0ea84-8b9d-4f07-8064-576d5c519747)
> See: https://github.com/pokt-network/poktroll/pull/662#discussion_r1668464237

## Goals

- Enumerate potential long-term & general solutions.
- Resolve tension caused by current import cycle workaround.
- Systematically prevent future import cycles in `pkg/client`.

## Deliverables

- [ ] A comment or link to a notion page which outlines the possible solutions, their pros and cons.
- [ ] One or more PRs which implement the chosen solution

## Non-goals / Non-deliverables

- Unrelated refactoring or re-organization.

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @bryanchriswhite 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@bryanchriswhite Is this still relevant or can we close it out?

**Comment by red-0ne** [comment]
> @bryanchriswhite Is this still relevant or can we close it out?

It is still relevant but depends on the outcome of https://github.com/pokt-network/poktroll/pull/697#issuecomment-2249018956 to move forward.

**Comment by Olshansk** [comment]
This does not seem urgent w.r.t to all the other feature work. Please lmk if this is a `Shanno Beta TestNet Launch` action item or a `quality of life` that can be done post mainnet.

**Comment by red-0ne** [comment]
Closing as per #697
