### ISSUE TITLE
[Application] Application Unbonding Periods

### ISSUE THREAD

**Issue by red-0ne** [pokt-network/poktroll#696]
## Objective

Prevent `Application`s from immediately unbonding when the MsgUnstake message is submitted.

## Deliverables

- [ ] A single PR mimicking the supplier unbonding period in #666
- [ ] A single PR mimicking the supplier unbonding period in #704

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @red-0ne 
**Co-owner**: @Olshansk

**Comment by Olshansk** [comment]
@red-0ne Could this just be a copy-paste of supplier unbonding?

**Comment by red-0ne** [comment]
> @red-0ne Could this just be a copy-paste of supplier unbonding?

Yes, it's basically the same logic as supplier unbonding.

**Comment by Olshansk** [comment]
@red-0ne DO you mind updating the ticket title + description to call out "unbonding" and reference the PR that will mimick the behaviour?
