### ISSUE TITLE
[TestNet] Ensure Genesis File is correct in TestNet

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#724]
## Objective

Stabilize TestNet seeds & full node synching.

Things work, eventually, but it should be much cleaner in such a controlled non-adversary environment.

## Origin Document

Seeing issues when running `kubectl logs testnet-validated-seed1-poktrolld-0 --namespace=testnet-validated-seed1`

![Screenshot 2024-08-06 at 7 30 27 PM](https://github.com/user-attachments/assets/fb6f9c57-5a7f-481a-8853-8815d093165f)

Seeing these issues when synching a node:

![Screenshot 2024-08-06 at 7 36 51 PM](https://github.com/user-attachments/assets/76d78568-a8fd-46fe-9d8d-6c6d0319dc57)

![Screenshot 2024-08-06 at 7 37 18 PM](https://github.com/user-attachments/assets/4ada7822-f5c8-4fa2-839b-2c78762203fd)

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas

**Comment by Olshansk** [comment]
@okdas Let's sync up on this next week. It's getting in the way of synching full nodes and understanding what's happening in testnet.

**Comment by okdas** [comment]
These particular errors are fine and expected as we're reusing the IP addresses when performing the regenesis.

Old nodes (that were provisioned using old genesis file) try to connect to the other nodes, including the first validator, causing these errors.

Not an issue,
