### ISSUE TITLE
[Core] Add support for an `unbonding` period after unstaking

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#73]
## Objective

When an actor (Application, Gateway, Supplier) unstakes, we need to decide if we need to have support for an unbonding period.

## Origin Document

[Ethereum Research](https://blog.ethereum.org/2014/11/25/proof-stake-learned-love-weak-subjectivity): Short-range attacks are possible if validators/sequencers do not have an unbonding period by forking and acting within a short few blocks.

[Cosmos SDK](https://docs.cosmos.network/main/build/modules/staking#validator): The cosmos SDK has support for an unbonding period with validators based on the principles above.

[BlockSci Research] 
https://hackmd.io/@blockscience/Sy7qq9bZT (Return Application Stake) 
https://hackmd.io/@blockscience/B1D4zwEWT (Return Gateway Stake)
https://hackmd.io/@blockscience/HyDcMDVWa (Return Supplier Stake) 

Ideas (to start the discussion) for having unbonding periods:
- Once QoS is implemented, a supplier that has received rewards needs to be staked/unbonding during the challenge period in case a challenge is submitted.
- Applications need to have time move to another Gateway if they are dependant on it to avoid loss of services

## Goals

- Determine which actors, if any, an unbonding period is necessary for pocket actors
- Implement unbonding if it is necessary

## Deliverables

- [ ] A short research document (i.e. 1-2 pager) describing whether bonding is necessary or not founded on fundamental crypto-economic principles 
- If it is deemed necessary:
	- [ ] A single PR (with tests) per actor that needs to have an unbonding period after staking
	- [ ] Governance values for the unbonding period on a per actor basis

## Non-goals / Non-deliverables

- Rolling your own unbonding solution (leverage Cosmos as much as possible)
- Doing the analysis to determine the value for the unbonding height if it ends up being necessary

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @h5law @RossiNYC

**Comment by RossiNYC** [comment]
@Olshansk - see the following adds from BlockSci (they ref unbonding as "return of stake" ]

[BlockSci Research]
https://hackmd.io/@blockscience/Sy7qq9bZT (Return Application Stake)
https://hackmd.io/@blockscience/B1D4zwEWT (Return Gateway Stake)
https://hackmd.io/@blockscience/HyDcMDVWa (Return Supplier Stake)

**Comment by Olshansk** [comment]
@RossiNYC Thanks for the extra details. One important thing to keep in mind is what the source of the requirements is.

BlockSci takes their requirements from us (the protocol team) and treats it as a black box (i.e. a probability) around which models/action chains are built to change the parameters. Specifically, the reason they have unbonding/returning in their action chains is that provided is a requirement and their models can help us determine the value (zero or non-zero) as they sweep.

This ticket is a precursor to their analysis to determine if unbonding period is needed at all in a more nuanced, crypto-economic requirement (i.e. see the links I posted related to shot-range attacks).

**Comment by RossiNYC** [comment]
@Olshansk Understood, will update here when these pages get final status and the parameters are updated (or tossed completely, etc.)

**Comment by Olshansk** [comment]
@h5law Since you'll be looking into adding a grace period for delegation, can you see if we should either update the goals/deliverables in this ticket or create a separate one? I think we should tackle it in the next iteraiton.

**Comment by h5law** [comment]
@Olshansk I will determine the cosmos-sdk tools we can leverage in this sort of thing for the grace period and update this issue accordingly with the discovered info

**Comment by Olshansk** [comment]
@h5law Please report what you find.

https://docs.cosmos.network/main/build/modules/staking

My gut is telling me that we're going to need to look at how the [x/staking module]() handles [unbonding](https://docs.cosmos.network/main/build/modules/staking#unbondingdelegation) under the hood, and "be inspired" by its implementation.

However, note that the `staking` module is one of the first ones that was implemented, so I'm sure a lot has changed since then. If you know anyone in the ecosystem whom you can ask "how would you do it if you were to do it all over again", we could learn a lot.
