### ISSUE TITLE
[Infra] Add pocketdex to the LocalNet deployment

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#752]
## Objective

Makeing the [pokckedex](https://github.com/pokt-network/pocketdex) indexer available in LocalNet.

## Origin Document

@jorgecuesta recently added k8s manifest files in [this PR](https://github.com/pokt-network/pocketdex/pull/14). Using this as a starting point for the poktroll [helm-charts](https://github.com/pokt-network/helm-charts) will be a great way to make LocalNet even more usefl.

## Goals

- Easily inspect indexed data in LocalNet

## Deliverables

- [ ] Make pocketdex part of the default `make localnet_up` environment

## Non-goals / Non-deliverables

- Making pocketedex part of DevNet

## General deliverables

---

**Creator**: @Olshansk 
**Co-Owners**: @jorgecuesta @okdas

**Comment by okdas** [comment]
@bryanchriswhite did this! :)

**Comment by Olshansk** [comment]
@okdas Are we going to add it to our DevNet/TestNet deployments?
