### ISSUE TITLE
[Docs] Document common supplier/node maintainer operations: pruning, snapshots & rollbacks

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#753]
## Objective

Document the following tools that we get "for free" from the [cosmos SDK](https://docs.cosmos.network/)

## Origin Document

Focus on the following tools:

![Screenshot 2024-08-22 at 10 21 02 AM](https://github.com/user-attachments/assets/b038bfd9-bef2-42ec-9fdc-13796caea713)

Discussion from [node chat discord channel](https://discord.com/channels/553741558869131266/564836328202567725) when a parameter changed in Morse.

![Screenshot 2024-08-22 at 10 23 28 AM](https://github.com/user-attachments/assets/bb32e470-3246-4778-8ad6-a4542a64fd62)

## Goals

- Document common tools that node operators (suppliers or not) need to know
- Make cosmos SDK tooling accessible to pocket network participants

## Deliverables

- [ ] Focus on `pruning`, `rollbacks` and `snapshots` in the documentation
- [ ] Ensure the docs are deployed to https://dev.poktroll.com/
- [ ] Review document in the [cosmos docs](https://docs.cosmos.network/) and other cosmos chains to see how much we can copy-paste w.r.t common tooling documentation
- [ ] Link to cosmos documentation where/when applicable

## Non-goals / Non-deliverables

- Use the pocket docs to provide all the details on these tools
- Customize any of these tools for immediate need

---

**Creator**: @Olshansk 
**Co-Owners**: @okdas

**Comment by okdas** [comment]
Going to close it in favor of #919
