### ISSUE TITLE
[Docs] Document and make a playbook on how to stake validators

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#754]
## Objective

Document the Cosmos SDK staking module for usage w.r.t [poktrolld](https://docs.cosmos.network/main/build/modules/staking) usage.

### Discord Channel

Focus on the following tools:

![Screenshot 2024-08-22 at 4 05 59 PM](https://github.com/user-attachments/assets/be13ff04-5d47-44ba-a7c5-44d7069544ac)

Discussion from [raid guild asking about staking](https://discord.com/channels/553741558869131266/1195132430844170342/1275951890479448105) when a parameter in Shannon

![Screenshot 2024-08-22 at 4 05 24 PM](https://github.com/user-attachments/assets/46ee096e-4b8d-4d6f-aab2-32fe9b79dc47)

### Conversaiton with the Cosmos SDK team

The following is a related conversation with the cosmos SDK team when we started building out our staking for non-validators. They recommended that we DO NOT use the staking module for this per the following conversation (it's legacy):

![Screenshot 2024-08-22 at 4 10 03 PM](https://github.com/user-attachments/assets/586d57db-62cf-4ef8-b765-756f5a67f187)
![Screenshot 2024-08-22 at 4 09 58 PM](https://github.com/user-attachments/assets/9a503754-56df-4d34-87f3-3baa2eab2541)

## Goals

- Document common tools for staking validators in a cosmos appchain
- Make cosmos SDK tooling accessible to pocket network participants
- Keep things simple
- Enable other individuals to run validators in SHannon

## Non-goals / Non-deliverables

- Use the pocket docs to provide all the details on these tools
- Customize any of these tools for immediate need
- Create redundant documentation

## Deliverables

- [ ] Focus on `poktrolld tx staking` and all downstream helpers
- [ ] Ensure the docs are deployed to https://dev.poktroll.com/
- [ ] Review document in the [cosmos docs](https://docs.cosmos.network/) and other cosmos chains to see how much we can copy-paste w.r.t common tooling documentation
- [ ] Link to cosmos documentation where/when applicable
- [ ] Increase the number of max validators on chain

```bash
$ poktrolld query staking params --node http://${VULTR_GROVE_TEST_IP}:26657
params:
  bond_denom: upokt
  historical_entries: 10000
  max_entries: 7
  max_validators: 1
  min_commission_rate: "0"
  unbonding_time: 504h0m0s
```
---

**Creator**: @Olshansk 
**Co-Owners**: @okdas

**Comment by okdas** [comment]
Closing in favor of  #919, where this and related work is caught.
