### ISSUE TITLE
[BUG][PROTOBUF] Ensure Compliance with Cosmos SDK Serialization Rules

### ISSUE THREAD

**Issue by okdas** [pokt-network/poktroll#759]
## Objective

Audit and update all protobufs in our codebase to ensure compliance with Cosmos SDK protobuf serialization requirements.

## Origin Document

Cosmos SDK has specific requirements for protobuf serialization to ensure deterministic behavior across all nodes. We need to ensure our codebase adheres to these requirements: https://docs.cosmos.network/main/build/architecture/adr-027-deterministic-protobuf-serialization#serialization-rules

## Goals

- Align our protobuf usage with Cosmos SDK best practices
- Ensure deterministic protobuf serialization across all parts of our system
- Improve overall system stability and reduce potential for serialization-related issues

## Deliverables

- [ ] Audit all protobuf definitions in the codebase
- [ ] Verify compliance with Cosmos SDK serialization rules
- [ ] Implement packed encoding for all repeated fields where appropriate
- [ ] Update any non-compliant protobuf definitions
- [ ] Create and run tests to verify deterministic serialization
- [ ] Document changes made and update relevant developer guidelines

## Non-goals / Non-deliverables

- Rewriting the entire protobuf system
- Implementing custom serialization methods outside of protobuf
- Addressing issues not related to protobuf serialization

## General deliverables

- [ ] **Comments**: Add explanatory comments in the code about protobuf serialization requirements
- [ ] **Testing**: Add new unit and integration tests to verify deterministic serialization
- [ ] **Documentation**: Update architectural READMEs to include information about protobuf serialization requirements and best practices

---

**Creator**: @okdas

**Comment by Olshansk** [comment]
Thanks for putting this issue together @okdas!

**Comment by okdas** [comment]
@Olshansk After further investigation, I believe this isn't necessary:

1. Following the apphash issue, I initially thought we might need to adjust protobuf definitions, but code changes are actually required.
2. Most ADR-27 recommendations are already covered by our use of `gogoproto` (included with Ignite).
3. ADR-27 has been in a 'Proposed' state since 2020, suggesting limited adoption (reasons unclear).
4. The only conflict between ADR-27 and our `gogoproto` usage is the omission of default values. We use the `nullable = false` attribute, which conflicts with ADR-27 but is strongly recommended by Ignite. I suggest we continue following Ignite's recommendation.

Given these points, implementing additional ADR-27 checks seems unnecessary for our current setup.
