### ISSUE TITLE
[Utility] Stake Weighted Supplier Rewards

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#763]
## Objective

Achieve feature parity with the `Stake Weighted Servicer (now known as Supplier) Rewards`.

## Origin Document

- `pocket-core` implementation can be found here: https://github.com/pokt-network/pocket-core/pull/1449
	- 👆 should be used as the reference for how to implement this

## Goals

- Achieve stake-weighted reward parity with Morse
- Clean implementation to enable other types of reward staking tiers post mainnet
- Clear documentation of how this works

## Deliverables

- [ ] Parity implementation of stake weighted rewards from Morse
- [ ] Docausrus document describing how this functionality works

## Non-goals / Non-deliverables

- Redesigning the stake weighted reward mechanism

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite

**Comment by red-0ne** [comment]
Closed by closing #825
