### ISSUE TITLE
[Relay Mining] Probabilistic Proofs <> Relay Mining Feedback Loop (i.e. Proportional Rewards)

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#781]
## Objective

Ensure off-chain relays serviced will have proportional rewards based on the relay difficulty.

## Origin Document

- Work on this started in [1] after uncovering this gap while discussing in [2]:
	- #771
	- #758

## Goals

- Fix critical missing gaps in the Relay Mining algorithm
- Ensure the protocol correctly rewards suppliers based on the work done (estimated), and not just the work committed

## Deliverables

- [x] Determine the number of estimated compute units as a function of relay difficulty
- [x] Use ☝️  in all tokenomics related logic 
- [ ] Document this change after finishing #665 

## Non-goals / Non-deliverables

- Updating the Relay Mining paper

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @Olshansk 
**Co-Owners**: @red-0ne @adshmh

**Comment by red-0ne** [comment]
Closing as per #840
