### ISSUE TITLE
[Shannon Explorer][Living Ticket] Poktscan Shannon Explorer

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/poktroll#903]
## Objective

Achieve parity (and beyond) with Morse's poktscan.com for Shannon.

## Origin Document

- Shannon's first explorer: https://shannon.testnet.pokt.network/poktroll/block
- Indexing framework: https://github.com/pokt-network/pocketdex/
- Discord Thread: https://discord.com/channels/553741558869131266/1205594535405817896 

## Goals

- Build the best network explorer possible with all the information anyone would want about Pocket Network and the Gateways operating on top of it

## Deliverables

- [ ] Achieve parity with the [existing Shannon Block Explorer](https://github.com/pokt-network/pocketdex/)
- [ ] Achieve parity with [poktscan.com](https://poktscan.com/) for Shannon
- [ ] Iterate on needs & requirements specific to a Shannon MainNet blocker exploerer

---

**Creator**: @Olshansk 
**Co-Owners**: @bryanchriswhite @jorgecuesta @RawthiL

**Comment by Olshansk** [comment]
<img width="1215" alt="Screenshot 2024-11-06 at 11 27 12 AM" src="https://github.com/user-attachments/assets/c679ed38-89fb-4aa4-9254-d9981a81f94e">

**Comment by jorgecuesta** [comment]
I think we almost achieve this, what you think @Olshansk ?

**Comment by Olshansk** [comment]
@jorgecuesta This is a "living ticket" so let's keep open for a couple more weeks in case new requests come in, but then we'll close this out as the MVP is nearly complete.

**Comment by Olshansk** [comment]
Closing this out and we'll create a new one with more concrete details / requirements when the time is right.!
