### ISSUE TITLE
[Application] Unstaking POKT to Leave the Network

### ISSUE THREAD

**Issue by RossiNYC** [pokt-network/poktroll#98]
## Objective

1. Define `Unstaking` & `Unbonding` (return of any existing POKT stake) rules for Shannon
2. Provide User Story & BDD-Gherkin to facilitate test automation 

## Origin Document

- [BlockSci - Application Unstake](https://hackmd.io/@blockscience/S1O2JPVWT)
- [BlockSci - Return Application Stake](https://hackmd.io/@blockscience/Sy7qq9bZT) (after unbond period)

## Goals

1. Developer understands `Unstaking` and `Unbonding` rules enough to test the features
2. Inform E2E automated testing 

## User Story & BDD

As an Application, I can unstake any positive remaining POKT balance which will be returned (i.e. unlocked) to me after the unbonding period so I can leave the pocket network.

```gherkin
Feature: Unstaking POKT Tokens from the Pocket Network

  Scenario: Application Unstakes POKT Tokens and Leaves the Network
    Given the Application has the pocketd binary installed
    And the Applications has a balance greater than "0" uPOKT
    And the Application has waited "n" seconds during the unbonding period
    And the Application is not part of an active session
    When the Application initiates the unstaking process
    Then the remaining POKT balance is returned (unlocked) to the Application
    And the Application successfully leaves the Pocket Network
```

### Constraints
- `Unstaking/Unbonding` is not possible to initiate while the application is part of an active session
- `Unstaking/Unbonding` is not possible to initiate until the last active session payment has been made (part or all of the current application stake is burned post-session)

## Deliverables / Acceptance Criteria

- [ ] 1. A test that proves an application **can** successfully unstake from the network
- [ ] 2. A test that proves an application **cannot** initiate unstaking during an active session or before the last active session has been settled (POKT spent during the last active session has been burned)
- [ ] 3. A test that proves an application positive POKT balance is returned in full if all qualifying conditions are met and after an unbonding period (as a configurable param)

## Non-goals / Non-deliverables

1. Exhaustively covering all edge cases
2. Establishing param default values 

## General deliverables

- [ ] **Comments**: Add/update TODOs and comments alongside the source code so it is easier to follow.
- [ ] **Testing**: Add new tests (unit and/or E2E) to the test suite.
- [ ] **Makefile**: Add new targets to the Makefile to make the new functionality easier to use.
- [ ] **Documentation**: Update architectural or development READMEs; use [mermaid](https://mermaid-js.github.io/mermaid/) diagrams where appropriate.

---

**Creator**: @RossiNYC 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
@RossiNYC Reviewed this issue and overall LGTM regarding the contest, deliverables, goals, etc! left a few edits w.r.t to the formatting so PTAL by reviewing the deltas (see screenshot below) and apply it elsewhere. Let's also start using the `e2e_story` label. Otherwise, 👌 

![Screenshot 2023-10-30 at 5 22 56 PM](https://github.com/pokt-network/poktroll/assets/1892194/f6260840-2329-48e8-897f-f7b0b0d6aa53)

**Comment by RossiNYC** [comment]
@Olshansk - yeah, I'll clean everything up in the next 24-48 hours, once I figured out you could /templates I started using that, but already had a few of these framed out
